// apps/svelte-demo/src/components/CommentForm.svelte
<script lang="ts">
  import type { CodeViewerTheme } from '@ngeenx/nx-code-viewer-utils';

  interface Props {
    line?: string;
    lineNumber?: number;
    theme?: CodeViewerTheme;
    onClose?: () => void;
  }

  let {
    line = '',
    lineNumber = 0,
    theme = 'dark',
    onClose = () => {},
  }: Props = $props();

  let comment = $state('');

  const truncatedLine = $derived(
    line.trim().length > 50 ? line.trim().substring(0, 50) + '...' : line.trim()
  );

  function cancel(): void {
    onClose();
  }

  function submit(): void {
    console.log(`Comment on line ${lineNumber}:`, comment);
    comment = '';
    onClose();
  }
</script>

<div class="comment-form {theme}">
  <div class="comment-header">
    <span class="comment-label">Comment on line {lineNumber}</span>
    <span class="line-preview">{truncatedLine}</span>
  </div>
  <textarea
    class="comment-input"
    bind:value={comment}
    placeholder="Add a comment..."
    rows="2"
  ></textarea>
  <div class="comment-actions">
    <button class="btn btn-cancel" type="button" onclick={cancel}>Cancel</button>
    <button class="btn btn-submit" type="button" onclick={submit}>Add Comment</button>
  </div>
</div>

<style>
  .comment-form { padding: 12px 16px; display: flex; flex-direction: column; gap: 8px; }
  .comment-form.dark { background: #1f2937; color: #e5e7eb; }
  .comment-form.light { background: #f9fafb; color: #1f2937; }
  .comment-header { display: flex; align-items: center; gap: 12px; font-size: 12px; }
  .comment-label { font-weight: 600; }
  .line-preview { opacity: 0.6; font-family: monospace; font-size: 11px; max-width: 300px; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }
  .comment-input { width: 97%; padding: 8px 12px; border-radius: 6px; font-size: 13px; resize: vertical; min-height: 60px; }
  .comment-form.dark .comment-input { background: #374151; border: 1px solid #4b5563; color: #e5e7eb; }
  .comment-form.light .comment-input { background: white; border: 1px solid #d1d5db; color: #1f2937; }
  .comment-input:focus { outline: none; border-color: #6366f1; box-shadow: 0 0 0 2px rgba(99, 102, 241, 0.2); }
  .comment-actions { display: flex; justify-content: flex-end; gap: 8px; }
  .btn { padding: 6px 12px; border-radius: 6px; font-size: 13px; font-weight: 500; cursor: pointer; transition: all 0.15s ease; }
  .btn-cancel { background: transparent; border: 1px solid #6b7280; color: #6b7280; }
  .btn-cancel:hover { background: rgba(107, 114, 128, 0.1); }
  .btn-submit { background: #6366f1; border: 1px solid #6366f1; color: white; }
  .btn-submit:hover { background: #4f46e5; border-color: #4f46e5; }
</style>

// apps/react-demo/src/app/components/comment-form.tsx
import { useState } from 'react';
import type { LineWidgetContext } from '@ngeenx/nx-react-code-viewer';

interface CommentFormProps extends LineWidgetContext {
  onClose: () => void;
}

export function CommentForm({ lineNumber, line, theme, onClose }: CommentFormProps) {
  const [comment, setComment] = useState('');

  const truncatedLine = (() => {
    const trimmed = line.trim();
    return trimmed.length > 50 ? trimmed.substring(0, 50) + '...' : trimmed;
  })();

  const cancel = () => onClose();

  const submit = () => {
    console.log(`Comment on line ${lineNumber}:`, comment);
    setComment('');
    onClose();
  };

  return (
    <div
      className={`comment-form ${theme}`}
      style={{
        padding: '12px 16px',
        display: 'flex',
        flexDirection: 'column',
        gap: 8,
        background: theme === 'dark' ? '#1f2937' : '#f9fafb',
        color: theme === 'dark' ? '#e5e7eb' : '#1f2937',
      }}
    >
      <div style={{ display: 'flex', alignItems: 'center', gap: 12, fontSize: 12 }}>
        <span style={{ fontWeight: 600 }}>Comment on line {lineNumber}</span>
        <span
          style={{
            opacity: 0.6,
            fontFamily: 'monospace',
            fontSize: 11,
            maxWidth: 300,
            overflow: 'hidden',
            textOverflow: 'ellipsis',
            whiteSpace: 'nowrap',
          }}
        >
          {truncatedLine}
        </span>
      </div>
      <textarea
        className="comment-input"
        value={comment}
        onChange={(e) => setComment(e.target.value)}
        placeholder="Add a comment..."
        rows={2}
        style={{
          width: '97%',
          padding: '8px 12px',
          borderRadius: 6,
          fontSize: 13,
          resize: 'vertical',
          minHeight: 60,
          background: theme === 'dark' ? '#374151' : 'white',
          border: `1px solid ${theme === 'dark' ? '#4b5563' : '#d1d5db'}`,
          color: theme === 'dark' ? '#e5e7eb' : '#1f2937',
        }}
      />
      <div style={{ display: 'flex', justifyContent: 'flex-end', gap: 8 }}>
        <button
          type="button"
          onClick={cancel}
          style={{
            padding: '6px 12px',
            borderRadius: 6,
            fontSize: 13,
            fontWeight: 500,
            cursor: 'pointer',
            transition: 'all 0.15s ease',
            background: 'transparent',
            border: '1px solid #6b7280',
            color: '#6b7280',
          }}
        >
          Cancel
        </button>
        <button
          type="button"
          onClick={submit}
          style={{
            padding: '6px 12px',
            borderRadius: 6,
            fontSize: 13,
            fontWeight: 500,
            cursor: 'pointer',
            transition: 'all 0.15s ease',
            background: '#6366f1',
            border: '1px solid #6366f1',
            color: 'white',
          }}
        >
          Add Comment
        </button>
      </div>
    </div>
  );
}
