// packages/client/ui/nx-svelte-code-viewer/src/lib/atoms/LineNumbers.svelte
<script lang="ts">
  import {
    generateLineNumbers,
    formatLineNumber,
    isLineHighlighted,
    isLineInCollapsedRange,
    type CodeViewerTheme,
    type CollapsedRangeState,
    type LineRange,
  } from '@ngeenx/nx-code-viewer-utils';
  import type { SvelteActiveInsertWidget } from '../types/svelte-code-viewer.types';

  interface Props {
    lineCount: number;
    theme?: CodeViewerTheme;
    hoveredLine?: number;
    highlightedLinesSet?: Set<number>;
    collapsedRangesState?: Map<string, CollapsedRangeState>;
    activeInsertWidget?: SvelteActiveInsertWidget | null;
    insertWidgetHeight?: number;
    onLineHover?: (lineNumber: number) => void;
    onCollapsedRangeToggle?: (range: LineRange) => void;
  }

  let {
    lineCount,
    theme = 'dark',
    hoveredLine = 0,
    highlightedLinesSet = new Set<number>(),
    collapsedRangesState = new Map(),
    activeInsertWidget = null,
    insertWidgetHeight = 0,
    onLineHover = () => {},
    onCollapsedRangeToggle = () => {},
  }: Props = $props();

  const lineNumbers = $derived(generateLineNumbers(lineCount));

  function getLineCollapseInfo(lineNumber: number) {
    return isLineInCollapsedRange(lineNumber, collapsedRangesState);
  }

  function isLineVisible(lineNumber: number): boolean {
    const info = getLineCollapseInfo(lineNumber);
    return !info.isCollapsed || info.isFirstLine;
  }

  function isHovered(lineNumber: number): boolean {
    return lineNumber === hoveredLine;
  }

  function isHighlighted(lineNumber: number): boolean {
    return isLineHighlighted(lineNumber, highlightedLinesSet);
  }

  function hasInsertWidgetAfter(lineNumber: number): boolean {
    return activeInsertWidget?.lineNumber === lineNumber;
  }
</script>

<div class="nx-line-numbers">
  <div class="line-numbers-container {theme}" aria-hidden="true">
    {#each lineNumbers as lineNumber (lineNumber)}
      {@const collapseInfo = getLineCollapseInfo(lineNumber)}
      {#if isLineVisible(lineNumber)}
        <div
          class="line-number"
          class:hovered={isHovered(lineNumber)}
          class:highlighted={isHighlighted(lineNumber)}
          class:collapsed-first={collapseInfo.isFirstLine}
          onmouseenter={() => onLineHover(lineNumber)}
        >
          {formatLineNumber(lineNumber, lineCount)}
        </div>

        {#if collapseInfo.isFirstLine && collapseInfo.range}
          <div
            class="line-number collapse-indicator"
            role="button"
            tabindex="0"
            aria-label="Expand {collapseInfo.hiddenCount} hidden {collapseInfo.hiddenCount === 1 ? 'line' : 'lines'}"
            onclick={() => onCollapsedRangeToggle(collapseInfo.range)}
            onkeydown={(e) => {
              if (e.key === 'Enter' || e.key === ' ') {
                e.preventDefault();
                onCollapsedRangeToggle(collapseInfo.range);
              }
            }}
          >
            <svg viewBox="0 0 24 24" width="18" height="18" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="m7 15 5 5 5-5" /><path d="m7 9 5-5 5 5" /></svg>
          </div>
        {/if}

        {#if hasInsertWidgetAfter(lineNumber)}
          <div
            class="insert-widget-placeholder"
            style="height: {insertWidgetHeight}px"
          ></div>
        {/if}
      {/if}
    {/each}
  </div>
</div>

// packages/client/ui/nx-react-code-viewer/src/lib/atoms/line-numbers/LineNumbers.tsx
import { memo, useMemo, useCallback } from 'react';
import {
  generateLineNumbers,
  formatLineNumber,
  isLineInCollapsedRange,
  type CodeViewerTheme,
  type CollapsedRangeState,
  type LineRange,
  type ActiveInsertWidget,
} from '@ngeenx/nx-code-viewer-utils';

interface LineNumbersProps {
  lineCount: number;
  theme?: CodeViewerTheme;
  hoveredLine?: number;
  highlightedLinesSet?: Set<number>;
  collapsedRangesState?: Map<string, CollapsedRangeState>;
  onLineHover?: (lineNumber: number) => void;
  onCollapsedRangeToggle?: (range: LineRange) => void;
  activeInsertWidget?: ActiveInsertWidget | null;
  insertWidgetHeight?: number;
}

export const LineNumbers = memo(function LineNumbers({
  lineCount,
  theme = 'dark',
  hoveredLine = 0,
  highlightedLinesSet = new Set(),
  collapsedRangesState = new Map(),
  onLineHover,
  onCollapsedRangeToggle,
  activeInsertWidget = null,
  insertWidgetHeight = 0,
}: LineNumbersProps) {
  const lineNumbers = useMemo(() => generateLineNumbers(lineCount), [lineCount]);

  const getCollapseInfo = useCallback((lineNumber: number) => {
    return isLineInCollapsedRange(lineNumber, collapsedRangesState);
  }, [collapsedRangesState]);

  return (
    <div className="nx-line-numbers">
      <div className={`line-numbers-container ${theme}`} aria-hidden="true">
        {lineNumbers.map(lineNumber => {
          const collapseInfo = getCollapseInfo(lineNumber);
          const isCollapsed = collapseInfo.isCollapsed && !collapseInfo.isFirstLine;

          if (isCollapsed) return null;

          return (
            <div key={lineNumber}>
              <div
                className={`line-number${hoveredLine === lineNumber ? ' hovered' : ''}${highlightedLinesSet.has(lineNumber) ? ' highlighted' : ''}${collapseInfo.isFirstLine ? ' collapsed-first' : ''}`}
                onMouseEnter={() => onLineHover?.(lineNumber)}
              >
                {formatLineNumber(lineNumber, lineCount)}
              </div>
              {collapseInfo.isFirstLine && collapseInfo.range && (
                <div
                  className="line-number collapse-indicator"
                  role="button"
                  tabIndex={0}
                  aria-label={`Expand ${collapseInfo.hiddenCount} hidden ${collapseInfo.hiddenCount === 1 ? 'line' : 'lines'}`}
                  onClick={() => onCollapsedRangeToggle?.(collapseInfo.range!)}
                  onKeyDown={e => {
                    if (e.key === 'Enter' || e.key === ' ') {
                      e.preventDefault();
                      onCollapsedRangeToggle?.(collapseInfo.range!);
                    }
                  }}
                >
                  <svg viewBox="0 0 24 24" width="18" height="18" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                    <path d="m7 15 5 5 5-5" />
                    <path d="m7 9 5-5 5 5" />
                  </svg>
                </div>
              )}
              {activeInsertWidget && activeInsertWidget.lineNumber === lineNumber && (
                <div className="insert-widget-placeholder" style={{ height: `${insertWidgetHeight}px` }} />
              )}
            </div>
          );
        })}
      </div>
    </div>
  );
});
