// packages/client/ui/nx-angular-code-viewer/src/lib/atoms/diff-collapsed-indicator/diff-collapsed-indicator.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  computed,
  input,
  output,
} from '@angular/core';
import type { CodeViewerTheme, DiffCollapsedRange } from '@ngeenx/nx-code-viewer-utils';

/**
 * DiffCollapsedIndicator Atom Component
 *
 * Displays a row indicating that diff lines are collapsed, with an expand toggle.
 * Styled to match the diff-line component layout.
 *
 * @example
 * ```html
 * <nx-diff-collapsed-indicator
 *   [theme]="'dark'"
 *   [range]="{ startIndex: 10, endIndex: 20 }"
 *   [hiddenCount]="10"
 *   [showLineNumbers]="true"
 *   (toggle)="onToggle()"
 * />
 * ```
 */
@Component({
  selector: 'nx-diff-collapsed-indicator',
  imports: [],
  templateUrl: './diff-collapsed-indicator.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { class: 'nx-diff-collapsed-indicator' },
})
export class DiffCollapsedIndicatorComponent {
  /**
   * Theme for styling
   */
  readonly theme = input<CodeViewerTheme>('dark');

  /**
   * The collapsed range
   */
  readonly range = input.required<DiffCollapsedRange>();

  /**
   * Number of hidden lines
   */
  readonly hiddenCount = input.required<number>();

  /**
   * Whether to show line number placeholders
   */
  readonly showLineNumbers = input<boolean>(true);

  /**
   * Whether to show the prefix placeholder
   */
  readonly showPrefix = input<boolean>(true);

  /**
   * Whether the range is currently expanded
   */
  readonly isExpanded = input<boolean>(false);

  /**
   * Emitted when the indicator is clicked to toggle expansion
   */
  readonly toggle = output<void>();

  /**
   * Computed CSS classes for the indicator
   */
  protected readonly indicatorClasses = computed(() => {
    const themeValue = this.theme();
    return `diff-collapsed-indicator ${themeValue}`.trim();
  });

  /**
   * Computed display text
   */
  protected readonly displayText = computed(() => {
    const count = this.hiddenCount();
    return count === 1 ? '1 line' : `${count} lines`;
  });

  /**
   * Computed aria label for accessibility
   */
  protected readonly ariaLabel = computed(() => {
    const count = this.hiddenCount();
    const expanded = this.isExpanded();
    const lines = count === 1 ? 'line' : 'lines';
    return expanded
      ? `Collapse ${count} ${lines}`
      : `Expand ${count} hidden ${lines}`;
  });

  /**
   * Handles click on the indicator
   */
  protected onToggle(): void {
    this.toggle.emit();
  }

  /**
   * Handles keyboard activation
   */
  protected onKeydown(event: KeyboardEvent): void {
    if (event.key === 'Enter' || event.key === ' ') {
      event.preventDefault();
      this.toggle.emit();
    }
  }
}

<div
  [class]="indicatorClasses()"
  role="button"
  tabindex="0"
  [attr.aria-expanded]="isExpanded()"
  [attr.aria-label]="ariaLabel()"
  (click)="onToggle()"
  (keydown)="onKeydown($event)">
  @if (showLineNumbers()) {
    <span class="line-number old"></span>
    <span class="line-number new"></span>
  }
  @if (showPrefix()) {
    <span class="prefix">
      <!-- Expand icon -->
      <svg
        viewBox="0 0 16 16"
        width="10"
        height="10"
        fill="none"
        stroke="currentColor"
        stroke-width="1.5"
        stroke-linecap="round"
        stroke-linejoin="round">
        @if (isExpanded()) {
          <path d="M4 6l4 4 4-4" />
        } @else {
          <path d="M6 4l4 4-4 4" />
        }
      </svg>
    </span>
  }
  <span class="content"> ... {{ displayText() }} </span>
</div>

// packages/client/ui/nx-vue-code-viewer/src/lib/atoms/diff-collapsed-indicator/DiffCollapsedIndicator.vue
<template>
  <div
    :class="indicatorClasses"
    role="button"
    tabindex="0"
    :aria-label="ariaLabel"
    @click="onToggle"
    @keydown="onKeydown"
  >
    <template v-if="showLineNumbers">
      <span class="line-number old" />
      <span class="line-number new" />
    </template>
    <span v-if="showPrefix" class="prefix" />
    <span class="collapse-content">
      <svg
        viewBox="0 0 24 24"
        width="14"
        height="14"
        fill="none"
        stroke="currentColor"
        stroke-width="2"
        stroke-linecap="round"
        stroke-linejoin="round"
        aria-hidden="true"
      >
        <path d="m7 15 5 5 5-5" />
        <path d="m7 9 5-5 5 5" />
      </svg>
      <span class="collapse-text">... {{ displayText }}</span>
    </span>
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue';
import type { CodeViewerTheme, DiffCollapsedRange } from '@ngeenx/nx-code-viewer-utils';

interface Props {
  theme?: CodeViewerTheme;
  range: DiffCollapsedRange;
  hiddenCount: number;
  showLineNumbers?: boolean;
  showPrefix?: boolean;
  isExpanded?: boolean;
}

const props = withDefaults(defineProps<Props>(), {
  theme: 'dark',
  showLineNumbers: true,
  showPrefix: true,
  isExpanded: false,
});

const emit = defineEmits<{
  toggle: [];
}>();

const indicatorClasses = computed(() => `diff-collapsed-indicator ${props.theme}`);

const displayText = computed(() => {
  const count = props.hiddenCount;
  return count === 1 ? '1 line' : `${count} lines`;
});

const ariaLabel = computed(() => {
  const count = props.hiddenCount;
  const lines = count === 1 ? 'line' : 'lines';
  return props.isExpanded ? `Collapse ${count} ${lines}` : `Expand ${count} hidden ${lines}`;
});

function onToggle(): void {
  emit('toggle');
}

function onKeydown(event: KeyboardEvent): void {
  if (event.key === 'Enter' || event.key === ' ') {
    event.preventDefault();
    emit('toggle');
  }
}
</script>
