// packages/client/ui/nx-vue-code-viewer/src/lib/atoms/diff-line/DiffLine.vue
<template>
  <div class="nx-diff-line">
  <div :class="lineClasses" @mouseenter="onMouseEnter">
    <!-- Left widgets -->
    <div v-if="leftWidgets.length > 0" class="line-widgets-left">
      <div
        v-for="(widget, i) in leftWidgets"
        :key="`left-${i}`"
        @click="onWidgetClick(widget)"
      >
        <component :is="widget.lineComponent" v-bind="widgetContext" />
      </div>
    </div>

    <span v-if="showLineNumbers" class="line-number old">{{ oldLineNum }}</span>
    <span v-if="showLineNumbers" class="line-number new">{{ newLineNum }}</span>
    <span v-if="showPrefix" class="prefix">{{ prefix }}</span>
    <span v-if="hasHighlightedContent" class="content" v-html="highlightedContent" />
    <span v-else class="content">{{ content }}</span>

    <!-- Right widgets -->
    <div v-if="rightWidgets.length > 0" class="line-widgets-right">
      <div
        v-for="(widget, i) in rightWidgets"
        :key="`right-${i}`"
        @click="onWidgetClick(widget)"
      >
        <component :is="widget.lineComponent" v-bind="widgetContext" />
      </div>
    </div>
  </div>
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue';
import {
  getDiffLinePrefix,
  getMatchingWidgets,
  type CodeViewerTheme,
  type DiffLine,
  type LineWidgetContext,
} from '@ngeenx/nx-code-viewer-utils';
import type { VueLineWidgetsInput, VueLineWidgetConfig, VueLineWidgetClickEvent } from '../../types/vue-code-viewer.types';

interface Props {
  line: DiffLine;
  theme?: CodeViewerTheme;
  showLineNumbers?: boolean;
  showPrefix?: boolean;
  isHighlighted?: boolean;
  lineIndex?: number;
  lineWidgets?: VueLineWidgetsInput;
  showWidgets?: boolean;
}

const props = withDefaults(defineProps<Props>(), {
  theme: 'dark',
  showLineNumbers: true,
  showPrefix: true,
  isHighlighted: false,
  lineIndex: 0,
  lineWidgets: () => [],
  showWidgets: false,
});

const emit = defineEmits<{
  lineHover: [lineIndex: number];
  lineWidgetClick: [event: VueLineWidgetClickEvent];
}>();

const lineClasses = computed(() => {
  const highlighted = props.isHighlighted ? 'highlighted' : '';
  return `diff-line ${props.line.type} ${props.theme} ${highlighted}`.trim();
});

const prefix = computed(() => getDiffLinePrefix(props.line.type));
const oldLineNum = computed(() => props.line.oldLineNumber !== undefined ? String(props.line.oldLineNumber) : '');
const newLineNum = computed(() => props.line.newLineNumber !== undefined ? String(props.line.newLineNumber) : '');
const content = computed(() => props.line.content);
const hasHighlightedContent = computed(() => !!props.line.highlightedContent);
const highlightedContent = computed(() => props.line.highlightedContent ?? '');
const lineNumber = computed(() => props.line.newLineNumber ?? props.line.oldLineNumber ?? 0);

const alwaysWidgets = computed<VueLineWidgetConfig[]>(() => {
  if (!props.lineWidgets?.length) return [];
  return (getMatchingWidgets(props.lineWidgets as any, content.value, lineNumber.value) as VueLineWidgetConfig[]).filter(w => w.display === 'always');
});

const hoverWidgets = computed<VueLineWidgetConfig[]>(() => {
  if (!props.lineWidgets?.length) return [];
  return (getMatchingWidgets(props.lineWidgets as any, content.value, lineNumber.value) as VueLineWidgetConfig[]).filter(w => w.display === 'hover');
});

const leftWidgets = computed(() => {
  const always = alwaysWidgets.value.filter(w => w.position === 'left');
  const hover = (props.showWidgets || props.isHighlighted) ? hoverWidgets.value.filter(w => w.position === 'left') : [];
  return [...always, ...hover];
});

const rightWidgets = computed(() => {
  const always = alwaysWidgets.value.filter(w => w.position === 'right');
  const hover = (props.showWidgets || props.isHighlighted) ? hoverWidgets.value.filter(w => w.position === 'right') : [];
  return [...always, ...hover];
});

const widgetContext = computed<LineWidgetContext>(() => ({
  line: content.value,
  lineNumber: lineNumber.value,
  theme: props.theme,
}));

function onMouseEnter(): void {
  emit('lineHover', props.lineIndex);
}

function onWidgetClick(widget: VueLineWidgetConfig): void {
  emit('lineWidgetClick', {
    lineNumber: lineNumber.value,
    line: content.value,
    widget,
  });
}
</script>

// packages/client/ui/nx-react-code-viewer/src/lib/atoms/diff-line/DiffLine.tsx
import { memo, useMemo } from 'react';
import {
  getDiffLinePrefix,
  getMatchingWidgets,
  type CodeViewerTheme,
  type DiffLine as DiffLineType,
  type LineWidgetClickEvent,
  type LineWidgetConfig,
  type LineWidgetContext,
  type LineWidgetsInput,
} from '@ngeenx/nx-code-viewer-utils';
import { LineWidgetHost } from '../line-widget-host';

interface DiffLineProps {
  line: DiffLineType;
  theme?: CodeViewerTheme;
  showLineNumbers?: boolean;
  showPrefix?: boolean;
  isHighlighted?: boolean;
  lineIndex?: number;
  lineWidgets?: LineWidgetsInput;
  showWidgets?: boolean;
  onLineHover?: (lineIndex: number) => void;
  onLineWidgetClick?: (event: LineWidgetClickEvent) => void;
}

export const DiffLine = memo(function DiffLine({
  line,
  theme = 'dark',
  showLineNumbers = true,
  showPrefix = true,
  isHighlighted = false,
  lineIndex = 0,
  lineWidgets,
  showWidgets = false,
  onLineHover,
  onLineWidgetClick,
}: DiffLineProps) {
  const lineClasses = useMemo(() => {
    const highlighted = isHighlighted ? 'highlighted' : '';
    return `diff-line ${line.type} ${theme} ${highlighted}`.trim();
  }, [line.type, theme, isHighlighted]);

  const prefix = useMemo(() => getDiffLinePrefix(line.type), [line.type]);

  const oldLineNum = useMemo(() => {
    return line.oldLineNumber !== undefined ? String(line.oldLineNumber) : '';
  }, [line.oldLineNumber]);

  const newLineNum = useMemo(() => {
    return line.newLineNumber !== undefined ? String(line.newLineNumber) : '';
  }, [line.newLineNumber]);

  const lineNumber = useMemo(() => {
    return line.newLineNumber ?? line.oldLineNumber ?? 0;
  }, [line.newLineNumber, line.oldLineNumber]);

  const widgetContext = useMemo<LineWidgetContext>(() => ({
    line: line.content,
    lineNumber,
    theme,
  }), [line.content, lineNumber, theme]);

  const alwaysWidgets = useMemo(() => {
    if (!lineWidgets) return [];
    return getMatchingWidgets(lineWidgets, line.content, lineNumber).filter(
      w => w.display === 'always'
    );
  }, [lineWidgets, line.content, lineNumber]);

  const hoverWidgets = useMemo(() => {
    if (!lineWidgets) return [];
    return getMatchingWidgets(lineWidgets, line.content, lineNumber).filter(
      w => w.display === 'hover'
    );
  }, [lineWidgets, line.content, lineNumber]);

  const leftWidgets = useMemo(() => {
    const always = alwaysWidgets.filter(w => w.position === 'left');
    const hover = (showWidgets || isHighlighted)
      ? hoverWidgets.filter(w => w.position === 'left')
      : [];
    return [...always, ...hover];
  }, [alwaysWidgets, hoverWidgets, showWidgets, isHighlighted]);

  const rightWidgets = useMemo(() => {
    const always = alwaysWidgets.filter(w => w.position === 'right');
    const hover = (showWidgets || isHighlighted)
      ? hoverWidgets.filter(w => w.position === 'right')
      : [];
    return [...always, ...hover];
  }, [alwaysWidgets, hoverWidgets, showWidgets, isHighlighted]);

  const handleWidgetClick = (widget: LineWidgetConfig) => {
    onLineWidgetClick?.({
      lineNumber,
      line: line.content,
      widget,
    });
  };

  return (
    <div className="nx-diff-line">
      <div className={lineClasses} onMouseEnter={() => onLineHover?.(lineIndex)}>
        {leftWidgets.length > 0 && (
          <div className="line-widgets-left">
            {leftWidgets.map((widget, i) => (
              <LineWidgetHost
                key={i}
                component={widget.lineComponent}
                context={widgetContext}
                position="left"
                theme={theme}
                onWidgetClick={() => handleWidgetClick(widget)}
              />
            ))}
          </div>
        )}

        {showLineNumbers && (
          <>
            <span className="line-number old">{oldLineNum}</span>
            <span className="line-number new">{newLineNum}</span>
          </>
        )}
        {showPrefix && <span className="prefix">{prefix}</span>}
        {line.highlightedContent ? (
          <span className="content" dangerouslySetInnerHTML={{ __html: line.highlightedContent }} />
        ) : (
          <span className="content">{line.content}</span>
        )}

        {rightWidgets.length > 0 && (
          <div className="line-widgets-right">
            {rightWidgets.map((widget, i) => (
              <LineWidgetHost
                key={i}
                component={widget.lineComponent}
                context={widgetContext}
                position="right"
                theme={theme}
                onWidgetClick={() => handleWidgetClick(widget)}
              />
            ))}
          </div>
        )}
      </div>
    </div>
  );
});
