// packages/client/ui/nx-svelte-code-viewer/src/lib/atoms/TabHeader.svelte
<script lang="ts">
  import { getFileIconUrl, type CodeViewerTheme } from '@ngeenx/nx-code-viewer-utils';

  interface Props {
    tabId: string;
    fileName: string;
    fileExtension?: string;
    isActive?: boolean;
    theme?: CodeViewerTheme;
    onTabClick?: (tabId: string) => void;
    onTabKeydown?: (event: KeyboardEvent) => void;
  }

  let {
    tabId,
    fileName,
    fileExtension = '',
    isActive = false,
    theme = 'dark',
    onTabClick = () => {},
    onTabKeydown = () => {},
  }: Props = $props();

  const iconUrl = $derived(fileExtension ? getFileIconUrl(fileExtension) : null);
</script>

<div class="nx-tab-header">
  <button
    type="button"
    role="tab"
    aria-selected={isActive}
    aria-controls="panel-{tabId}"
    id="tab-{tabId}"
    tabindex={isActive ? 0 : -1}
    class="{theme} {isActive ? 'active' : ''}"
    onclick={() => onTabClick(tabId)}
    onkeydown={onTabKeydown}
  >
    {#if iconUrl}
      <img src={iconUrl} class="file-icon" alt={fileName} />
    {/if}
    <span class="file-name">{fileName}</span>
  </button>
</div>

// packages/client/ui/nx-react-code-viewer/src/lib/atoms/tab-header/TabHeader.tsx
import { memo, useMemo } from 'react';
import { getFileIconUrl, type CodeViewerTheme } from '@ngeenx/nx-code-viewer-utils';

interface TabHeaderProps {
  tabId: string;
  fileName: string;
  fileExtension?: string;
  isActive?: boolean;
  theme?: CodeViewerTheme;
  onTabClick?: (tabId: string) => void;
  onTabKeydown?: (event: React.KeyboardEvent) => void;
}

export const TabHeader = memo(function TabHeader({
  tabId,
  fileName,
  fileExtension = '',
  isActive = false,
  theme = 'dark',
  onTabClick,
  onTabKeydown,
}: TabHeaderProps) {
  const iconUrl = useMemo(() => {
    return fileExtension ? getFileIconUrl(fileExtension) : null;
  }, [fileExtension]);

  return (
    <div className="nx-tab-header">
      <button
        type="button"
        role="tab"
        aria-selected={isActive}
        aria-controls={`panel-${tabId}`}
        id={`tab-${tabId}`}
        tabIndex={isActive ? 0 : -1}
        className={`${theme} ${isActive ? 'active' : ''}`}
        onClick={() => onTabClick?.(tabId)}
        onKeyDown={onTabKeydown}
      >
        {iconUrl && (
          <img src={iconUrl} className="file-icon" alt={fileName} />
        )}
        <span className="file-name">{fileName}</span>
      </button>
    </div>
  );
});
