// packages/client/ui/nx-vue-code-viewer/src/lib/organisms/multi-code-viewer/MultiCodeViewer.vue
<template>
  <article :class="`${theme} border-${borderStyle}`" class="nx-multi-code-viewer">
    <div v-if="borderStyle === 'grid-cross'" class="border-overlay">
      <div class="border-top" /><div class="border-bottom" /><div class="border-left" /><div class="border-right" />
      <div class="corner-cross corner-top-left-h" /><div class="corner-cross corner-top-left-v" />
      <div class="corner-cross corner-top-right-h" /><div class="corner-cross corner-top-right-v" />
      <div class="corner-cross corner-bottom-left-h" /><div class="corner-cross corner-bottom-left-v" />
      <div class="corner-cross corner-bottom-right-h" /><div class="corner-cross corner-bottom-right-v" />
    </div>
    <div v-if="borderStyle === 'corner-intersection'" class="border-overlay">
      <div class="border-top-extended" /><div class="border-bottom-extended" /><div class="border-left-extended" /><div class="border-right-extended" />
    </div>

    <TabBar
      :tabs="tabs"
      :activeTabId="activeTabId"
      :theme="theme"
      @tab-change="onTabChange"
    />

    <div class="tab-panels">
      <div
        v-for="tab in tabs"
        :key="tab.id"
        role="tabpanel"
        :id="`panel-${tab.id}`"
        :aria-labelledby="`tab-${tab.id}`"
        :class="{ hidden: tab.id !== activeTabId, active: tab.id === activeTabId }"
      >
        <CodeViewer
          v-if="isCodeTab(tab)"
          :code="tab.code"
          :language="tab.language || 'plaintext'"
          :theme="theme"
          :shikiTheme="shikiTheme"
          :showHeader="showContentHeader"
          :title="tab.fileName"
          :fileExtension="tab.fileExtension || ''"
          :showLineNumbers="tab.showLineNumbers ?? true"
          :showCopyButton="tab.showCopyButton ?? true"
          :maxHeight="tab.maxHeight || ''"
          :wordWrap="tab.wordWrap ?? false"
          :highlightedLines="tab.highlightedLines"
          borderStyle="none"
          @code-copied="onCodeCopied(tab.id)"
        />

        <DiffViewer
          v-if="isDiffTab(tab)"
          :diff="tab.diff || ''"
          :oldCode="tab.oldCode || ''"
          :newCode="tab.newCode || ''"
          :language="tab.language || 'plaintext'"
          :theme="theme"
          :shikiTheme="shikiTheme"
          :showHeader="showContentHeader"
          :showLineNumbers="tab.showLineNumbers ?? true"
          :viewMode="tab.viewMode || 'unified'"
          :maxHeight="tab.maxHeight || ''"
          :oldFileName="tab.oldFileName || ''"
          :newFileName="tab.newFileName || ''"
          :fileExtension="tab.fileExtension || ''"
          borderStyle="none"
        />
      </div>
    </div>
  </article>
</template>

<script setup lang="ts">
import { ref, computed, watch } from 'vue';
import {
  DEFAULT_MULTI_CODE_VIEWER_CONFIG,
  isCodeTabItem,
  isDiffTabItem,
  type CodeViewerBorderStyle,
  type CodeViewerTheme,
  type MultiCodeViewerTabItem,
  type ShikiThemeName,
  type TabChangeEvent,
} from '@ngeenx/nx-code-viewer-utils';
import { TabBar } from '../../molecules/tab-bar';
import { CodeViewer } from '../code-viewer';
import { DiffViewer } from '../diff-viewer';

interface Props {
  tabs: readonly MultiCodeViewerTabItem[];
  theme?: CodeViewerTheme;
  shikiTheme?: ShikiThemeName;
  borderStyle?: CodeViewerBorderStyle;
  showContentHeader?: boolean;
  initialActiveTabId?: string;
}

const props = withDefaults(defineProps<Props>(), {
  theme: () => DEFAULT_MULTI_CODE_VIEWER_CONFIG.theme,
  borderStyle: () => DEFAULT_MULTI_CODE_VIEWER_CONFIG.borderStyle,
  showContentHeader: () => DEFAULT_MULTI_CODE_VIEWER_CONFIG.showContentHeader,
  initialActiveTabId: '',
});

const emit = defineEmits<{
  activeTabChange: [event: TabChangeEvent];
  codeCopied: [tabId: string];
}>();

const activeTabIdInternal = ref<string>('');

const activeTabId = computed(() => {
  if (activeTabIdInternal.value) return activeTabIdInternal.value;
  if (props.initialActiveTabId) return props.initialActiveTabId;
  return props.tabs.length > 0 ? props.tabs[0].id : '';
});

watch(
  () => props.initialActiveTabId,
  (initial) => {
    if (initial) activeTabIdInternal.value = initial;
  },
  { immediate: true }
);

const isCodeTab = isCodeTabItem;
const isDiffTab = isDiffTabItem;

function onTabChange(tabId: string): void {
  const previousId = activeTabId.value;
  const tabs = props.tabs;
  const newIndex = tabs.findIndex(tab => tab.id === tabId);

  if (newIndex >= 0 && tabId !== previousId) {
    activeTabIdInternal.value = tabId;
    emit('activeTabChange', {
      previousTabId: previousId || null,
      currentTabId: tabId,
      currentIndex: newIndex,
    });
  }
}

function onCodeCopied(tabId: string): void {
  emit('codeCopied', tabId);
}
</script>

// packages/client/ui/nx-angular-code-viewer/src/lib/organisms/multi-code-viewer/multi-code-viewer.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  computed,
  effect,
  input,
  output,
  signal,
  untracked,
} from '@angular/core';
import type {
  CodeViewerBorderStyle,
  CodeViewerTheme,
  MultiCodeViewerTabItem,
  TabChangeEvent,
} from '../../types';
import {
  DEFAULT_MULTI_CODE_VIEWER_CONFIG,
  isCodeTabItem,
  isDiffTabItem,
} from '../../types';
import { TabBarComponent } from '../../molecules/tab-bar';
import { CodeViewerComponent } from '../code-viewer';
import { DiffViewerComponent } from '../diff-viewer';

/**
 * MultiCodeViewer Organism Component
 *
 * Provides a tabbed interface for displaying multiple code viewers
 * and/or diff viewers. Each tab has its own file name, icon, and content.
 *
 * @example
 * ```html
 * <nx-multi-code-viewer
 *   [tabs]="[
 *     { id: 'ts', type: 'code', fileName: 'app.ts', code: tsCode, language: 'typescript' },
 *     { id: 'html', type: 'code', fileName: 'app.html', code: htmlCode, language: 'html' }
 *   ]"
 *   [theme]="'dark'"
 *   [borderStyle]="'classic'"
 *   (activeTabChange)="onTabChange($event)"
 * />
 * ```
 */
@Component({
  selector: 'nx-multi-code-viewer',
  standalone: true,
  imports: [TabBarComponent, CodeViewerComponent, DiffViewerComponent],
  templateUrl: './multi-code-viewer.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { class: 'nx-multi-code-viewer' },
})
export class MultiCodeViewerComponent {
  // ═══════════════════════════════════════════════════════════════════════════
  // INPUTS
  // ═══════════════════════════════════════════════════════════════════════════

  /**
   * Array of tab items (code or diff)
   */
  readonly tabs = input.required<readonly MultiCodeViewerTabItem[]>();

  /**
   * Color theme
   */
  readonly theme = input<CodeViewerTheme>(
    DEFAULT_MULTI_CODE_VIEWER_CONFIG.theme
  );

  /**
   * Border style variant
   */
  readonly borderStyle = input<CodeViewerBorderStyle>(
    DEFAULT_MULTI_CODE_VIEWER_CONFIG.borderStyle
  );

  /**
   * Whether to show individual content headers inside tabs
   */
  readonly showContentHeader = input<boolean>(
    DEFAULT_MULTI_CODE_VIEWER_CONFIG.showContentHeader
  );

  /**
   * Initial active tab ID (defaults to first tab)
   */
  readonly initialActiveTabId = input<string>('');

  // ═══════════════════════════════════════════════════════════════════════════
  // OUTPUTS
  // ═══════════════════════════════════════════════════════════════════════════

  /**
   * Emits when the active tab changes
   */
  readonly activeTabChange = output<TabChangeEvent>();

  /**
   * Emits when code is copied from a code tab
   */
  readonly codeCopied = output<string>();

  // ═══════════════════════════════════════════════════════════════════════════
  // STATE
  // ═══════════════════════════════════════════════════════════════════════════

  /**
   * Currently active tab ID
   */
  private readonly activeTabIdInternal = signal<string>('');

  // ═══════════════════════════════════════════════════════════════════════════
  // COMPUTED
  // ═══════════════════════════════════════════════════════════════════════════

  /**
   * Current active tab ID (internal or from first tab)
   */
  protected readonly activeTabId = computed(() => {
    const internal = this.activeTabIdInternal();
    if (internal) return internal;

    const initial = this.initialActiveTabId();
    if (initial) return initial;

    const tabs = this.tabs();
    return tabs.length > 0 ? tabs[0].id : '';
  });

  /**
   * Currently active tab item
   */
  protected readonly activeTab = computed(() => {
    const tabs = this.tabs();
    const activeId = this.activeTabId();
    return tabs.find(tab => tab.id === activeId) ?? null;
  });

  /**
   * Type guards for template
   */
  protected readonly isCodeTab = isCodeTabItem;
  protected readonly isDiffTab = isDiffTabItem;

  // ═══════════════════════════════════════════════════════════════════════════
  // EFFECTS
  // ═══════════════════════════════════════════════════════════════════════════

  constructor() {
    // Initialize active tab from initialActiveTabId input
    effect(() => {
      const initial = this.initialActiveTabId();
      if (initial) {
        untracked(() => {
          this.activeTabIdInternal.set(initial);
        });
      }
    });
  }

  // ═══════════════════════════════════════════════════════════════════════════
  // METHODS
  // ═══════════════════════════════════════════════════════════════════════════

  /**
   * Handle tab change from tab bar
   */
  protected onTabChange(tabId: string): void {
    const previousId = this.activeTabId();
    const tabs = this.tabs();
    const newIndex = tabs.findIndex(tab => tab.id === tabId);

    if (newIndex >= 0 && tabId !== previousId) {
      this.activeTabIdInternal.set(tabId);
      this.activeTabChange.emit({
        previousTabId: previousId || null,
        currentTabId: tabId,
        currentIndex: newIndex,
      });
    }
  }

  /**
   * Handle code copied event from code viewer
   */
  protected onCodeCopied(tabId: string): void {
    this.codeCopied.emit(tabId);
  }
}

<article [class]="theme() + ' border-' + borderStyle()">
  <!-- Border overlay for grid-cross style -->
  @if (borderStyle() === 'grid-cross') {
    <div class="border-overlay">
      <div class="border-top"></div>
      <div class="border-bottom"></div>
      <div class="border-left"></div>
      <div class="border-right"></div>
      <div class="corner-cross corner-top-left-h"></div>
      <div class="corner-cross corner-top-left-v"></div>
      <div class="corner-cross corner-top-right-h"></div>
      <div class="corner-cross corner-top-right-v"></div>
      <div class="corner-cross corner-bottom-left-h"></div>
      <div class="corner-cross corner-bottom-left-v"></div>
      <div class="corner-cross corner-bottom-right-h"></div>
      <div class="corner-cross corner-bottom-right-v"></div>
    </div>
  }

  <!-- Border overlay for corner-intersection style -->
  @if (borderStyle() === 'corner-intersection') {
    <div class="border-overlay">
      <div class="border-top-extended"></div>
      <div class="border-bottom-extended"></div>
      <div class="border-left-extended"></div>
      <div class="border-right-extended"></div>
    </div>
  }

  <!-- Tab bar -->
  <nx-tab-bar
    [tabs]="tabs()"
    [activeTabId]="activeTabId()"
    [theme]="theme()"
    (tabChange)="onTabChange($event)" />

  <!-- Tab panels container -->
  <div class="tab-panels">
    @for (tab of tabs(); track tab.id) {
      <div
        role="tabpanel"
        [attr.id]="'panel-' + tab.id"
        [attr.aria-labelledby]="'tab-' + tab.id"
        [class.hidden]="tab.id !== activeTabId()"
        [class.active]="tab.id === activeTabId()">
        @if (isCodeTab(tab)) {
          <nx-code-viewer
            [code]="tab.code"
            [language]="tab.language || 'plaintext'"
            [theme]="theme()"
            [shikiTheme]="shikiTheme()"
            [showHeader]="showContentHeader()"
            [title]="tab.fileName"
            [fileExtension]="tab.fileExtension || ''"
            [showLineNumbers]="tab.showLineNumbers ?? true"
            [showCopyButton]="tab.showCopyButton ?? true"
            [maxHeight]="tab.maxHeight || ''"
            [wordWrap]="tab.wordWrap ?? false"
            [highlightedLines]="tab.highlightedLines"
            borderStyle="none"
            (codeCopied)="onCodeCopied(tab.id)" />
        }

        @if (isDiffTab(tab)) {
          <nx-diff-viewer
            [diff]="tab.diff || ''"
            [oldCode]="tab.oldCode || ''"
            [newCode]="tab.newCode || ''"
            [language]="tab.language || 'plaintext'"
            [theme]="theme()"
            [shikiTheme]="shikiTheme()"
            [showHeader]="showContentHeader()"
            [showLineNumbers]="tab.showLineNumbers ?? true"
            [viewMode]="tab.viewMode || 'unified'"
            [maxHeight]="tab.maxHeight || ''"
            [oldFileName]="tab.oldFileName || ''"
            [newFileName]="tab.newFileName || ''"
            [fileExtension]="tab.fileExtension || ''"
            borderStyle="none" />
        }
      </div>
    }
  </div>
</article>
