// packages/client/ui/nx-react-code-viewer/src/lib/atoms/code-header/CodeHeader.tsx
import { memo, useMemo } from 'react';
import {
  getLanguageDisplayName,
  getFileIconUrl,
  getExtensionFromLanguage,
  type CodeViewerLanguage,
  type CodeViewerTheme,
} from '@ngeenx/nx-code-viewer-utils';

interface CodeHeaderProps {
  language?: CodeViewerLanguage;
  title?: string;
  theme?: CodeViewerTheme;
  fileExtension?: string;
}

export const CodeHeader = memo(function CodeHeader({
  language = 'plaintext',
  title = '',
  theme = 'dark',
  fileExtension = '',
}: CodeHeaderProps) {
  const displayText = useMemo(() => title || getLanguageDisplayName(language), [title, language]);

  const iconUrl = useMemo(() => {
    if (fileExtension) return getFileIconUrl(fileExtension);
    const langExt = getExtensionFromLanguage(language);
    return langExt ? getFileIconUrl(langExt) : null;
  }, [fileExtension, language]);

  return (
    <div className="nx-code-header">
      <header className={theme}>
        <div className="title-container">
          {iconUrl && <img src={iconUrl} className="file-icon" alt={title} />}
          <span className="title">{displayText}</span>
        </div>
      </header>
    </div>
  );
});

// packages/client/ui/nx-vue-code-viewer/src/lib/atoms/code-header/CodeHeader.vue
<template>
  <header :class="theme" class="nx-code-header">
    <div class="title-container">
      <img v-if="iconUrl" :src="iconUrl" class="file-icon" :alt="title" />
      <span class="title">{{ displayText }}</span>
    </div>
  </header>
</template>

<script setup lang="ts">
import { computed } from 'vue';
import {
  getLanguageDisplayName,
  getFileIconUrl,
  getExtensionFromLanguage,
  type CodeViewerLanguage,
  type CodeViewerTheme,
} from '@ngeenx/nx-code-viewer-utils';

interface Props {
  language?: CodeViewerLanguage;
  title?: string;
  theme?: CodeViewerTheme;
  fileExtension?: string;
}

const props = withDefaults(defineProps<Props>(), {
  language: 'plaintext',
  title: '',
  theme: 'dark',
  fileExtension: '',
});

const displayText = computed(() => {
  if (props.title) return props.title;
  return getLanguageDisplayName(props.language);
});

const iconUrl = computed<string | null>(() => {
  if (props.fileExtension) return getFileIconUrl(props.fileExtension);
  const langExt = getExtensionFromLanguage(props.language);
  if (langExt) return getFileIconUrl(langExt);
  return null;
});
</script>
