// apps/react-demo/src/app/app.tsx
import { Routes, Route } from 'react-router-dom';
import { ThemeProvider } from './hooks/useTheme';
import { Layout } from './layout/Layout';
import LandingPage from './pages/LandingPage';
import BasicExamplesPage from './pages/BasicExamplesPage';
import DisplayOptionsPage from './pages/DisplayOptionsPage';
import LineHighlightingPage from './pages/LineHighlightingPage';
import InteractiveFeaturesPage from './pages/InteractiveFeaturesPage';
import BorderStylesPage from './pages/BorderStylesPage';
import ThemingPage from './pages/ThemingPage';
import DiffViewerPage from './pages/DiffViewerPage';
import MultiCodeViewerPage from './pages/MultiCodeViewerPage';
import ColumnCodeViewerPage from './pages/ColumnCodeViewerPage';
import PlaygroundPage from './pages/PlaygroundPage';

export function App() {
  return (
    <ThemeProvider>
      <Routes>
        <Route path="/" element={<Layout />}>
          <Route index element={<LandingPage />} />
          <Route path="basic-examples" element={<BasicExamplesPage />} />
          <Route path="display-options" element={<DisplayOptionsPage />} />
          <Route path="line-highlighting" element={<LineHighlightingPage />} />
          <Route path="interactive-features" element={<InteractiveFeaturesPage />} />
          <Route path="border-styles" element={<BorderStylesPage />} />
          <Route path="theming" element={<ThemingPage />} />
          <Route path="diff-viewer" element={<DiffViewerPage />} />
          <Route path="multi-code-viewer" element={<MultiCodeViewerPage />} />
          <Route path="column-code-viewer" element={<ColumnCodeViewerPage />} />
          <Route path="playground" element={<PlaygroundPage />} />
        </Route>
      </Routes>
    </ThemeProvider>
  );
}

export default App;

// apps/svelte-demo/src/App.svelte
<script lang="ts">
  import Router from 'svelte-spa-router';
  import Layout from './layout/Layout.svelte';
  import LandingPage from './pages/LandingPage.svelte';
  import BasicExamplesPage from './pages/BasicExamplesPage.svelte';
  import DisplayOptionsPage from './pages/DisplayOptionsPage.svelte';
  import LineHighlightingPage from './pages/LineHighlightingPage.svelte';
  import InteractiveFeaturesPage from './pages/InteractiveFeaturesPage.svelte';
  import BorderStylesPage from './pages/BorderStylesPage.svelte';
  import ThemingPage from './pages/ThemingPage.svelte';
  import DiffViewerPage from './pages/DiffViewerPage.svelte';
  import MultiCodeViewerPage from './pages/MultiCodeViewerPage.svelte';
  import ColumnCodeViewerPage from './pages/ColumnCodeViewerPage.svelte';
  import PlaygroundPage from './pages/PlaygroundPage.svelte';
  import { wrap } from 'svelte-spa-router/wrap';

  const routes = {
    '/': wrap({ component: LandingPage }),
    '/basic-examples': wrap({ component: BasicExamplesPage }),
    '/display-options': wrap({ component: DisplayOptionsPage }),
    '/line-highlighting': wrap({ component: LineHighlightingPage }),
    '/interactive-features': wrap({ component: InteractiveFeaturesPage }),
    '/border-styles': wrap({ component: BorderStylesPage }),
    '/theming': wrap({ component: ThemingPage }),
    '/diff-viewer': wrap({ component: DiffViewerPage }),
    '/multi-code-viewer': wrap({ component: MultiCodeViewerPage }),
    '/column-code-viewer': wrap({ component: ColumnCodeViewerPage }),
    '/playground': wrap({ component: PlaygroundPage }),
  };
</script>

<Layout>
  <Router {routes} />
</Layout>
