// packages/client/ui/nx-vue-code-viewer/src/lib/molecules/code-block/CodeBlock.vue
<template>
  <div class="code-block-wrapper">
    <CopyButton
      v-if="showCopyButton"
      class="copy-button"
      :state="copyState"
      :theme="theme"
      @copy-click="onCopyClick"
    />

    <div
      class="code-block-container"
      :style="containerStyle"
      @mouseleave="onLineHover(0)"
    >
      <LineNumbers
        v-if="showLineNumbers"
        :lineCount="lineCount"
        :theme="theme"
        :hoveredLine="hoveredLine"
        :highlightedLinesSet="highlightedLinesSet"
        :collapsedRangesState="collapsedRangesState"
        :activeInsertWidget="activeInsertWidget"
        :insertWidgetHeight="insertWidgetHeight"
        @line-hover="onLineHover"
        @collapsed-range-toggle="onCollapsedRangeToggle"
      />

      <CodeContent
        :content="content"
        :rawCode="rawCode"
        :theme="theme"
        :wordWrap="wordWrap"
        :isLoading="isLoading"
        :hoveredLine="hoveredLine"
        :highlightedLinesSet="highlightedLinesSet"
        :focusedLinesSet="focusedLinesSet"
        :collapsedRangesState="collapsedRangesState"
        :processedReferences="processedReferences"
        :lineWidgets="lineWidgets"
        :activeInsertWidget="activeInsertWidget"
        @line-hover="onLineHover"
        @reference-click="onReferenceClick"
        @reference-hover="onReferenceHover"
        @collapsed-range-toggle="onCollapsedRangeToggle"
        @line-widget-click="onLineWidgetClick"
        @insert-widget-close="onInsertWidgetClose"
        @insert-widget-height-change="onInsertWidgetHeightChange"
      />
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, computed } from 'vue';
import type {
  CodeViewerTheme,
  CollapsedRangeState,
  LineRange,
  ProcessedReference,
  ReferenceHoverEvent,
} from '@ngeenx/nx-code-viewer-utils';
import type {
  VueLineWidgetsInput,
  VueActiveInsertWidget,
  VueLineWidgetClickEvent,
} from '../../types/vue-code-viewer.types';
import type { CopyButtonState } from '@ngeenx/nx-code-viewer-utils';
import { CodeContent } from '../../atoms/code-content';
import { LineNumbers } from '../../atoms/line-numbers';
import { CopyButton } from '../../atoms/copy-button';

interface Props {
  content: string | null;
  rawCode?: string;
  lineCount: number;
  theme?: CodeViewerTheme;
  showLineNumbers?: boolean;
  wordWrap?: boolean;
  maxHeight?: string;
  isLoading?: boolean;
  showCopyButton?: boolean;
  copyState?: CopyButtonState;
  copyClick?: () => void;
  highlightedLinesSet?: Set<number>;
  focusedLinesSet?: Set<number>;
  processedReferences?: Map<string, ProcessedReference>;
  collapsedRangesState?: Map<string, CollapsedRangeState>;
  lineWidgets?: VueLineWidgetsInput;
}

const props = withDefaults(defineProps<Props>(), {
  rawCode: '',
  theme: 'dark',
  showLineNumbers: true,
  wordWrap: false,
  maxHeight: '',
  isLoading: false,
  showCopyButton: true,
  copyState: 'idle',
  copyClick: () => {},
  highlightedLinesSet: () => new Set(),
  focusedLinesSet: () => new Set(),
  processedReferences: () => new Map(),
  collapsedRangesState: () => new Map(),
  lineWidgets: () => [],
});

const emit = defineEmits<{
  referenceClick: [reference: ProcessedReference];
  referenceHover: [event: ReferenceHoverEvent];
  collapsedRangeToggle: [range: LineRange];
  lineWidgetClick: [event: VueLineWidgetClickEvent];
}>();

const hoveredLine = ref<number>(0);
const activeInsertWidget = ref<VueActiveInsertWidget | null>(null);
const insertWidgetHeight = ref<number>(0);

const containerStyle = computed(() => {
  return props.maxHeight ? { 'max-height': props.maxHeight } : {};
});

function onLineHover(lineNumber: number): void {
  hoveredLine.value = lineNumber;
}

function onCopyClick(): void {
  props.copyClick();
}

function onReferenceClick(reference: ProcessedReference): void {
  emit('referenceClick', reference);
}

function onReferenceHover(event: ReferenceHoverEvent): void {
  emit('referenceHover', event);
}

function onCollapsedRangeToggle(range: LineRange): void {
  emit('collapsedRangeToggle', range);
}

function onLineWidgetClick(event: VueLineWidgetClickEvent): void {
  const current = activeInsertWidget.value;

  if (current && current.lineNumber === event.lineNumber && current.widget === event.widget) {
    activeInsertWidget.value = null;
  } else if (event.widget.insertComponent) {
    activeInsertWidget.value = {
      lineNumber: event.lineNumber,
      widget: event.widget,
      line: event.line,
    };
  }

  emit('lineWidgetClick', event);
}

function onInsertWidgetClose(): void {
  activeInsertWidget.value = null;
}

function onInsertWidgetHeightChange(height: number): void {
  insertWidgetHeight.value = height;
}
</script>

// packages/client/ui/nx-angular-code-viewer/src/lib/molecules/code-block/code-block.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  computed,
  input,
  output,
  signal,
} from '@angular/core';
import { NgStyle } from '@angular/common';
import type { SafeHtml } from '@angular/platform-browser';
import type {
  ActiveInsertWidget,
  CodeViewerTheme,
  CollapsedRangeState,
  CopyButtonState,
  LineRange,
  LineWidgetClickEvent,
  LineWidgetsInput,
  ProcessedReference,
  ReferenceHoverEvent,
} from '../../types';
import { LineNumbersComponent } from '../../atoms/line-numbers';
import { CodeContentComponent } from '../../atoms/code-content';
import { CopyButtonComponent } from '../../atoms/copy-button';

/**
 * CodeBlock Molecule Component
 *
 * Combines line numbers and code content atoms into a cohesive code block.
 * Handles layout and scrolling for the code display area.
 *
 * @example
 * ```html
 * <nx-code-block
 *   [content]="highlightedHtml()"
 *   [lineCount]="10"
 *   [theme]="'dark'"
 *   [showLineNumbers]="true"
 *   [wordWrap]="false"
 *   [maxHeight]="'400px'"
 *   [lineWidgets]="widgets"
 * />
 * ```
 */
@Component({
  selector: 'nx-code-block',
  standalone: true,
  imports: [
    NgStyle,
    LineNumbersComponent,
    CodeContentComponent,
    CopyButtonComponent,
  ],
  templateUrl: './code-block.component.html',
  styleUrl: './code-block.component.css',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class CodeBlockComponent {
  // ═══════════════════════════════════════════════════════════════════════════
  // INPUTS
  // ═══════════════════════════════════════════════════════════════════════════

  /**
   * Highlighted HTML content
   */
  readonly content = input.required<SafeHtml | null>();

  /**
   * Raw code string for extracting line text
   */
  readonly rawCode = input<string>('');

  /**
   * Number of lines in the code
   */
  readonly lineCount = input.required<number>();

  /**
   * Theme for styling
   */
  readonly theme = input<CodeViewerTheme>('dark');

  /**
   * Whether to show line numbers
   */
  readonly showLineNumbers = input<boolean>(true);

  /**
   * Whether to wrap long lines
   */
  readonly wordWrap = input<boolean>(false);

  /**
   * Maximum height with scroll
   */
  readonly maxHeight = input<string>('');

  /**
   * Whether content is loading
   */
  readonly isLoading = input<boolean>(false);

  /**
   * Whether to show the copy button
   */
  readonly showCopyButton = input<boolean>(true);

  /**
   * Current state of the copy button
   */
  readonly copyState = input<CopyButtonState>('idle');

  /**
   * Copy button click handler
   */
  readonly copyClick = input<() => void>(() => {});

  /**
   * Set of pre-configured highlighted line numbers
   */
  readonly highlightedLinesSet = input<Set<number>>(new Set());

  /**
   * Set of focused line numbers (lines NOT in this set will be blurred)
   */
  readonly focusedLinesSet = input<Set<number>>(new Set());

  /**
   * Map of processed reference IDs to their data
   */
  readonly processedReferences = input<Map<string, ProcessedReference>>(
    new Map()
  );

  /**
   * Map of collapsed range states
   */
  readonly collapsedRangesState = input<Map<string, CollapsedRangeState>>(
    new Map()
  );

  /**
   * Line widget configurations
   */
  readonly lineWidgets = input<LineWidgetsInput>([]);

  // ═══════════════════════════════════════════════════════════════════════════
  // OUTPUTS
  // ═══════════════════════════════════════════════════════════════════════════

  /**
   * Emitted when a reference is clicked
   */
  readonly referenceClick = output<ProcessedReference>();

  /**
   * Emitted when a reference is hovered
   */
  readonly referenceHover = output<ReferenceHoverEvent>();

  /**
   * Emitted when a collapsed range indicator is clicked
   */
  readonly collapsedRangeToggle = output<LineRange>();

  /**
   * Emitted when a line widget is clicked
   */
  readonly lineWidgetClick = output<LineWidgetClickEvent>();

  // ═══════════════════════════════════════════════════════════════════════════
  // STATE
  // ═══════════════════════════════════════════════════════════════════════════

  /**
   * Currently hovered line index (1-based, 0 means no line hovered)
   */
  protected readonly hoveredLine = signal<number>(0);

  /**
   * Currently active insert widget
   */
  protected readonly activeInsertWidget = signal<ActiveInsertWidget | null>(null);

  // ═══════════════════════════════════════════════════════════════════════════
  // COMPUTED
  // ═══════════════════════════════════════════════════════════════════════════

  /**
   * Computed container styles for max height
   */
  protected readonly containerStyle = computed(() => {
    const height = this.maxHeight();
    return height ? { 'max-height': height } : {};
  });

  /**
   * Whether component has max height set (for conditional scrolling)
   */
  protected readonly hasMaxHeight = computed(() => !!this.maxHeight());

  // ═══════════════════════════════════════════════════════════════════════════
  // EVENT HANDLERS
  // ═══════════════════════════════════════════════════════════════════════════

  /**
   * Handler for line hover events
   */
  protected onLineHover(lineNumber: number): void {
    this.hoveredLine.set(lineNumber);
  }

  /**
   * Handler for copy button click
   */
  protected onCopyClick(): void {
    this.copyClick()();
  }

  /**
   * Handler for reference click events
   */
  protected onReferenceClick(reference: ProcessedReference): void {
    this.referenceClick.emit(reference);
  }

  /**
   * Handler for reference hover events
   */
  protected onReferenceHover(event: ReferenceHoverEvent): void {
    this.referenceHover.emit(event);
  }

  /**
   * Handler for collapsed range toggle events
   */
  protected onCollapsedRangeToggle(range: LineRange): void {
    this.collapsedRangeToggle.emit(range);
  }

  /**
   * Handler for line widget click events
   */
  protected onLineWidgetClick(event: LineWidgetClickEvent): void {
    // Toggle insert widget
    const currentActive = this.activeInsertWidget();
    if (
      currentActive &&
      currentActive.lineNumber === event.lineNumber &&
      currentActive.widget === event.widget
    ) {
      // Same widget clicked, close it
      this.activeInsertWidget.set(null);
    } else if (event.widget.insertComponent) {
      // Different widget with insert component, open it
      this.activeInsertWidget.set({
        lineNumber: event.lineNumber,
        widget: event.widget,
        line: event.line,
      });
    }

    // Emit the event to parent
    this.lineWidgetClick.emit(event);
  }
}

<div class="code-block-wrapper">
  @if (showCopyButton()) {
    <nx-copy-button
      class="copy-button"
      [state]="copyState()"
      [theme]="theme()"
      (copyClick)="onCopyClick()" />
  }

  <div
    class="code-block-container"
    [ngStyle]="containerStyle()"
    (mouseleave)="onLineHover(0)">
    @if (showLineNumbers()) {
      <nx-line-numbers
        [lineCount]="lineCount()"
        [theme]="theme()"
        [hoveredLine]="hoveredLine()"
        [highlightedLinesSet]="highlightedLinesSet()"
        [collapsedRangesState]="collapsedRangesState()"
        [activeInsertWidget]="activeInsertWidget()"
        [insertWidgetHeight]="insertWidgetHeight()"
        (lineHover)="onLineHover($event)"
        (collapsedRangeToggle)="onCollapsedRangeToggle($event)" />
    }

    <nx-code-content
      [content]="content()"
      [rawCode]="rawCode()"
      [theme]="theme()"
      [wordWrap]="wordWrap()"
      [isLoading]="isLoading()"
      [hoveredLine]="hoveredLine()"
      [highlightedLinesSet]="highlightedLinesSet()"
      [focusedLinesSet]="focusedLinesSet()"
      [collapsedRangesState]="collapsedRangesState()"
      [processedReferences]="processedReferences()"
      [lineWidgets]="lineWidgets()"
      [activeInsertWidget]="activeInsertWidget()"
      (lineHover)="onLineHover($event)"
      (referenceClick)="onReferenceClick($event)"
      (referenceHover)="onReferenceHover($event)"
      (collapsedRangeToggle)="onCollapsedRangeToggle($event)"
      (lineWidgetClick)="onLineWidgetClick($event)"
      (insertWidgetClose)="onInsertWidgetClose()"
      (insertWidgetHeightChange)="onInsertWidgetHeightChange($event)" />
  </div>
</div>
