// packages/client/ui/nx-angular-code-viewer/src/lib/atoms/code-header/code-header.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  computed,
  input,
} from '@angular/core';
import type { CodeViewerLanguage, CodeViewerTheme } from '@ngeenx/nx-code-viewer-utils';
import {
  getLanguageDisplayName,
  getFileIconUrl,
  getExtensionFromLanguage,
} from '@ngeenx/nx-code-viewer-utils';

/**
 * CodeHeader Atom Component
 *
 * Displays header section for code blocks with title/language and file icon.
 *
 * @example
 * ```html
 * <nx-code-header
 *   [language]="'typescript'"
 *   [title]="'Example'"
 *   [theme]="'dark'"
 * />
 * ```
 */
@Component({
  selector: 'nx-code-header',
  standalone: true,
  imports: [],
  templateUrl: './code-header.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { class: 'nx-code-header' },
})
export class CodeHeaderComponent {
  /**
   * Programming language of the code
   */
  readonly language = input<CodeViewerLanguage>('plaintext');

  /**
   * Optional title to display instead of language
   */
  readonly title = input<string>('');

  /**
   * Theme for styling
   */
  readonly theme = input<CodeViewerTheme>('dark');

  /**
   * File extension for icon display (e.g., '.ts', '.js')
   */
  readonly fileExtension = input<string>('');

  /**
   * Computed display text (title or language name)
   */
  protected readonly displayText = computed(() => {
    const titleValue = this.title();
    if (titleValue) {
      return titleValue;
    }
    return getLanguageDisplayName(this.language());
  });

  /**
   * Computed icon URL from file extension or language
   */
  protected readonly iconUrl = computed(() => {
    const ext = this.fileExtension();
    if (ext) {
      return getFileIconUrl(ext);
    }

    // Fallback: guess extension from language
    const langExt = getExtensionFromLanguage(this.language());
    if (langExt) {
      return getFileIconUrl(langExt);
    }

    return null;
  });
}

<header [class]="theme()">
  <div class="title-container">
    @if (iconUrl()) {
      <img [src]="iconUrl()" class="file-icon" alt="" />
    }
    <span class="title">
      {{ displayText() }}
    </span>
  </div>

  @if (showCopyButton()) {
    <ngn-copy-button
      [state]="copyState()"
      [theme]="theme()"
      (copyClick)="onCopyClick()"
    />
  }
</header>

// packages/client/ui/nx-react-code-viewer/src/lib/atoms/code-header/CodeHeader.tsx
import { memo, useMemo } from 'react';
import {
  getLanguageDisplayName,
  getFileIconUrl,
  getExtensionFromLanguage,
  type CodeViewerLanguage,
  type CodeViewerTheme,
} from '@ngeenx/nx-code-viewer-utils';

interface CodeHeaderProps {
  language?: CodeViewerLanguage;
  title?: string;
  theme?: CodeViewerTheme;
  fileExtension?: string;
}

export const CodeHeader = memo(function CodeHeader({
  language = 'plaintext',
  title = '',
  theme = 'dark',
  fileExtension = '',
}: CodeHeaderProps) {
  const displayText = useMemo(() => title || getLanguageDisplayName(language), [title, language]);

  const iconUrl = useMemo(() => {
    if (fileExtension) return getFileIconUrl(fileExtension);
    const langExt = getExtensionFromLanguage(language);
    return langExt ? getFileIconUrl(langExt) : null;
  }, [fileExtension, language]);

  return (
    <div className="nx-code-header">
      <header className={theme}>
        <div className="title-container">
          {iconUrl && <img src={iconUrl} className="file-icon" alt={title} />}
          <span className="title">{displayText}</span>
        </div>
      </header>
    </div>
  );
});
