// packages/client/ui/nx-svelte-code-viewer/src/lib/molecules/CodeBlockStoryWrapper.svelte
<script lang="ts">
  import { countLines, type CodeViewerTheme, type CopyButtonState } from '@ngeenx/nx-code-viewer-utils';
  import { useCodeHighlighter } from '../composables';
  import CodeBlock from './CodeBlock.svelte';

  interface Props {
    code?: string;
    theme?: CodeViewerTheme;
    showLineNumbers?: boolean;
    wordWrap?: boolean;
    maxHeight?: string;
    isLoading?: boolean;
    showCopyButton?: boolean;
    copyState?: CopyButtonState;
    highlightedLinesSet?: Set<number>;
  }

  let {
    code = '',
    theme = 'dark',
    showLineNumbers = true,
    wordWrap = false,
    maxHeight = '',
    isLoading = false,
    showCopyButton = true,
    copyState = 'idle',
    highlightedLinesSet = new Set<number>(),
  }: Props = $props();

  const highlighter = useCodeHighlighter();
  let highlightedHtml: string | null = $state(null);
  let lineCount = $derived(countLines(code));

  function handleCopyClick() {
    console.log('Copy clicked');
  }

  $effect(() => {
    if (!code) {
      highlightedHtml = null;
      return;
    }
    highlighter.highlightToHtml({ code, language: 'typescript', theme }).then(result => {
      highlightedHtml = result.html;
    });
  });
</script>

<CodeBlock
  content={highlightedHtml}
  {lineCount}
  {theme}
  {showLineNumbers}
  {wordWrap}
  {maxHeight}
  {isLoading}
  {showCopyButton}
  {copyState}
  copyClick={handleCopyClick}
  {highlightedLinesSet}
/>

// packages/client/ui/nx-react-code-viewer/src/lib/molecules/code-block/CodeBlockStoryWrapper.tsx
import React, { useState, useEffect } from 'react';
import { CodeBlock } from './CodeBlock';
import { countLines, type CodeViewerTheme, type CopyButtonState } from '@ngeenx/nx-code-viewer-utils';
import { useCodeHighlighter } from '../../hooks';

interface Props {
  code?: string;
  theme?: CodeViewerTheme;
  showLineNumbers?: boolean;
  wordWrap?: boolean;
  maxHeight?: string;
  isLoading?: boolean;
  showCopyButton?: boolean;
  copyState?: CopyButtonState;
  highlightedLinesSet?: Set<number>;
}

export function CodeBlockStoryWrapper({
  code = '',
  theme = 'dark',
  showLineNumbers = true,
  wordWrap = false,
  maxHeight = '',
  isLoading = false,
  showCopyButton = true,
  copyState = 'idle',
  highlightedLinesSet = new Set<number>(),
}: Props) {
  const highlighter = useCodeHighlighter();
  const [highlightedHtml, setHighlightedHtml] = useState<string | null>(null);
  const lineCount = countLines(code);

  useEffect(() => {
    if (!code) { setHighlightedHtml(null); return; }
    highlighter.highlightToHtml({ code, language: 'typescript', theme }).then(result => {
      setHighlightedHtml(result.html);
    });
  }, [code, theme]);

  return (
    <CodeBlock
      content={highlightedHtml}
      lineCount={lineCount}
      theme={theme}
      showLineNumbers={showLineNumbers}
      wordWrap={wordWrap}
      maxHeight={maxHeight}
      isLoading={isLoading}
      showCopyButton={showCopyButton}
      copyState={copyState}
      onCopyClick={() => console.log('Copy clicked')}
      highlightedLinesSet={highlightedLinesSet}
    />
  );
}
