// packages/client/ui/nx-angular-code-viewer/src/lib/organisms/diff-viewer/diff-viewer.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  computed,
  effect,
  inject,
  input,
  OnDestroy,
  output,
  signal,
  untracked,
} from '@angular/core';
import {
  DEFAULT_DIFF_VIEWER_CONFIG,
  parseDiff,
  computeDiff,
  getDiffStats,
  parseDiffCollapsedRanges,
  createDiffCollapsedRangesState,
  diffRangeToKey,
  type CodeViewerBorderStyle,
  type CodeViewerLanguage,
  type CodeViewerTheme,
  type DiffCollapsedLinesInput,
  type DiffCollapsedRange,
  type DiffCollapsedRangeState,
  type DiffCollapsedRangeToggleEvent,
  type DiffHunk,
  type DiffLine,
  type DiffViewMode,
  type LineWidgetClickEvent,
  type LineWidgetsInput,
  type ParsedDiff,
  type ShikiThemeName,
  type ShikiThemePair,
} from '@ngeenx/nx-code-viewer-utils';
import { CodeHighlighterService } from '../../services';
import { CodeHeaderComponent } from '../../atoms/code-header';
import { DiffBlockComponent } from '../../molecules/diff-block';

/**
 * DiffViewer Organism Component
 *
 * Main component for displaying code diffs with syntax highlighting.
 * Supports both unified diff strings and oldCode/newCode input modes.
 *
 * @example
 * ```html
 * <!-- Using unified diff string -->
 * <nx-diff-viewer
 *   [diff]="gitDiffOutput"
 *   [language]="'typescript'"
 *   [theme]="'dark'"
 *   [viewMode]="'unified'"
 * />
 *
 * <!-- Using structured data -->
 * <nx-diff-viewer
 *   [oldCode]="originalCode"
 *   [newCode]="modifiedCode"
 *   [language]="'typescript'"
 *   [viewMode]="'split'"
 * />
 * ```
 */
@Component({
  selector: 'nx-diff-viewer',
  imports: [CodeHeaderComponent, DiffBlockComponent],
  templateUrl: './diff-viewer.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { class: 'nx-diff-viewer' },
})
export class DiffViewerComponent implements OnDestroy {
  /**
   * Abort controller for canceling pending highlight operations
   */
  private highlightAbortController: AbortController | null = null;

  /**
   * Injected services
   */
  private readonly highlighterService = inject(CodeHighlighterService);

  // ═══════════════════════════════════════════════════════════════════════════
  // INPUTS - Option 1: Unified diff string
  // ═══════════════════════════════════════════════════════════════════════════

  /**
   * Unified diff string (git diff format)
   */
  readonly diff = input<string>('');

  // ═══════════════════════════════════════════════════════════════════════════
  // INPUTS - Option 2: Structured data
  // ═══════════════════════════════════════════════════════════════════════════

  /**
   * Original code (for computing diff)
   */
  readonly oldCode = input<string>('');

  /**
   * Modified code (for computing diff)
   */
  readonly newCode = input<string>('');

  // ═══════════════════════════════════════════════════════════════════════════
  // INPUTS - Configuration
  // ═══════════════════════════════════════════════════════════════════════════

  /**
   * Display mode: unified or split
   */
  readonly viewMode = input<DiffViewMode>(DEFAULT_DIFF_VIEWER_CONFIG.viewMode);

  /**
   * Programming language for header display
   */
  readonly language = input<CodeViewerLanguage>(
    DEFAULT_DIFF_VIEWER_CONFIG.language
  );

  /**
   * Color theme
   */
  readonly theme = input<CodeViewerTheme>(DEFAULT_DIFF_VIEWER_CONFIG.theme);

  /**
   * Shiki theme name for syntax highlighting
   * When provided, overrides the default theme-based mapping (github-dark/github-light)
   * See ShikiThemeName type for available options
   */
  readonly shikiTheme = input<ShikiThemeName>();

  /**
   * Paired Shiki themes for automatic light/dark swapping.
   *
   * When the component's `theme` input flips, the resolver picks
   * `shikiThemes.dark` or `shikiThemes.light` to highlight with.
   * Either slot may be omitted; missing modes fall back to the
   * built-in `github-dark` / `github-light` defaults.
   *
   * Lower precedence than the explicit single `shikiTheme` input:
   * if both are supplied, `shikiTheme` wins. See `resolveShikiTheme()`
   * in `@ngeenx/nx-code-viewer-utils` for the precedence chain.
   */
  readonly shikiThemes = input<ShikiThemePair>();

  /**
   * Whether to show line numbers
   */
  readonly showLineNumbers = input<boolean>(
    DEFAULT_DIFF_VIEWER_CONFIG.showLineNumbers
  );

  /**
   * Whether to show header section
   */
  readonly showHeader = input<boolean>(DEFAULT_DIFF_VIEWER_CONFIG.showHeader);

  /**
   * Maximum height with scrolling
   */
  readonly maxHeight = input<string>('');

  /**
   * Old file name (for header display)
   */
  readonly oldFileName = input<string>('');

  /**
   * New file name (for header display)
   */
  readonly newFileName = input<string>('');

  /**
   * File extension for icon display
   */
  readonly fileExtension = input<string>('');

  /**
   * Border style variant
   * - 'classic': Standard rounded border (default)
   * - 'grid-cross': Grid borders with corner cross marks
   * - 'corner-intersection': Long grid borders extending beyond corners
   * - 'none': No border styling
   */
  readonly borderStyle = input<CodeViewerBorderStyle>('classic');

  /**
   * Collapsed line ranges (0-based global indices)
   */
  readonly collapsedLines = input<DiffCollapsedLinesInput>();

  /**
   * Line widget configurations
   */
  readonly lineWidgets = input<LineWidgetsInput>();

  // ═══════════════════════════════════════════════════════════════════════════
  // OUTPUTS
  // ═══════════════════════════════════════════════════════════════════════════

  /**
   * Emitted when a collapsed range is expanded or collapsed
   */
  readonly collapsedRangeToggle = output<DiffCollapsedRangeToggleEvent>();

  /**
   * Emitted when a line widget is clicked
   */
  readonly lineWidgetClick = output<LineWidgetClickEvent>();

  // ═══════════════════════════════════════════════════════════════════════════
  // STATE
  // ═══════════════════════════════════════════════════════════════════════════

  /**
   * Parsed diff result
   */
  private readonly parsedDiff = signal<ParsedDiff>({ hunks: [] });

  /**
   * State for collapsed ranges (tracks which ranges are expanded)
   */
  protected readonly collapsedRangesState = signal<
    Map<string, DiffCollapsedRangeState>
  >(new Map());

  // ═══════════════════════════════════════════════════════════════════════════
  // COMPUTED
  // ═══════════════════════════════════════════════════════════════════════════

  /**
   * Diff hunks for the diff block
   */
  protected readonly hunks = computed(() => this.parsedDiff().hunks);

  /**
   * Whether there are any changes to display
   */
  protected readonly hasChanges = computed(
    () => this.parsedDiff().hunks.length > 0
  );

  /**
   * Display title from filenames or language
   */
  protected readonly displayTitle = computed(() => {
    const newFile = this.newFileName() || this.parsedDiff().newFileName;
    const oldFile = this.oldFileName() || this.parsedDiff().oldFileName;

    if (newFile && oldFile && newFile !== oldFile) {
      return `${oldFile} → ${newFile}`;
    }

    return newFile || oldFile || '';
  });

  /**
   * Diff statistics
   */
  protected readonly stats = computed(() => getDiffStats(this.parsedDiff()));

  // ═══════════════════════════════════════════════════════════════════════════
  // EFFECTS
  // ═══════════════════════════════════════════════════════════════════════════

  constructor() {
    // Effect to parse/compute diff and apply syntax highlighting
    effect(() => {
      const diffValue = this.diff();
      const oldCodeValue = this.oldCode();
      const newCodeValue = this.newCode();
      const languageValue = this.language();
      const themeValue = this.theme();
      const shikiThemeValue = this.shikiTheme();
      const shikiThemesValue = this.shikiThemes();

      untracked(() => {
        void this.processDiff(
          diffValue,
          oldCodeValue,
          newCodeValue,
          languageValue,
          themeValue,
          shikiThemeValue,
          shikiThemesValue
        );
      });
    });

    // Effect to initialize collapsed ranges state when input changes
    effect(() => {
      const collapsedInput = this.collapsedLines();

      untracked(() => {
        const parsedRanges = parseDiffCollapsedRanges(collapsedInput);
        this.collapsedRangesState.set(
          createDiffCollapsedRangesState(parsedRanges)
        );
      });
    });
  }

  // ═══════════════════════════════════════════════════════════════════════════
  // LIFECYCLE
  // ═══════════════════════════════════════════════════════════════════════════

  ngOnDestroy(): void {
    this.abortPendingHighlight();
  }

  // ═══════════════════════════════════════════════════════════════════════════
  // PRIVATE METHODS
  // ═══════════════════════════════════════════════════════════════════════════

  /**
   * Process diff and apply syntax highlighting
   */
  private async processDiff(
    diffValue: string,
    oldCodeValue: string,
    newCodeValue: string,
    language: CodeViewerLanguage,
    theme: CodeViewerTheme,
    shikiTheme?: ShikiThemeName,
    shikiThemes?: ShikiThemePair
  ): Promise<void> {
    // Abort any pending highlight operation
    this.abortPendingHighlight();

    let parsed: ParsedDiff;

    if (diffValue) {
      parsed = parseDiff(diffValue);
    } else if (oldCodeValue || newCodeValue) {
      parsed = computeDiff(oldCodeValue, newCodeValue);
    } else {
      this.parsedDiff.set({ hunks: [] });
      return;
    }

    // Set initial parsed diff (without highlighting)
    this.parsedDiff.set(parsed);

    // Skip highlighting for plaintext
    if (language === 'plaintext') {
      return;
    }

    // Create abort controller for highlighting
    this.highlightAbortController = new AbortController();
    const { signal } = this.highlightAbortController;

    // Reconstruct old and new code from diff lines
    const oldLines: string[] = [];
    const newLines: string[] = [];

    for (const hunk of parsed.hunks) {
      for (const line of hunk.lines) {
        if (line.type === 'removed' || line.type === 'unchanged') {
          oldLines.push(line.content);
        }
        if (line.type === 'added' || line.type === 'unchanged') {
          newLines.push(line.content);
        }
      }
    }

    // Highlight both code versions
    const [highlightedOldLines, highlightedNewLines] = await Promise.all([
      this.highlighterService.highlightLines({
        code: oldLines.join('\n'),
        language,
        theme,
        signal,
        shikiTheme,
        shikiThemes,
      }),
      this.highlighterService.highlightLines({
        code: newLines.join('\n'),
        language,
        theme,
        signal,
        shikiTheme,
        shikiThemes,
      }),
    ]);

    if (signal.aborted) {
      return;
    }

    // Apply highlighted content to diff lines
    const highlightedHunks = this.applyHighlighting(
      parsed.hunks,
      highlightedOldLines,
      highlightedNewLines
    );

    this.parsedDiff.set({
      ...parsed,
      hunks: highlightedHunks,
    });
  }

  /**
   * Apply highlighted content to diff lines
   */
  private applyHighlighting(
    hunks: readonly DiffHunk[],
    highlightedOldLines: string[],
    highlightedNewLines: string[]
  ): DiffHunk[] {
    let oldIndex = 0;
    let newIndex = 0;

    return hunks.map(hunk => ({
      ...hunk,
      lines: hunk.lines.map((line): DiffLine => {
        let highlightedContent: string | undefined;

        if (line.type === 'removed') {
          highlightedContent = highlightedOldLines[oldIndex++];
        } else if (line.type === 'added') {
          highlightedContent = highlightedNewLines[newIndex++];
        } else if (line.type === 'unchanged') {
          // For unchanged lines, use old content (both are the same)
          highlightedContent = highlightedOldLines[oldIndex++];
          newIndex++;
        }

        return highlightedContent ? { ...line, highlightedContent } : line;
      }),
    }));
  }

  /**
   * Aborts any pending highlight operation
   */
  private abortPendingHighlight(): void {
    if (this.highlightAbortController) {
      this.highlightAbortController.abort();
      this.highlightAbortController = null;
    }
  }

  /**
   * Handler for collapsed range toggle events from diff block
   */
  protected onCollapsedRangeToggle(range: DiffCollapsedRange): void {
    const key = diffRangeToKey(range);
    const currentState = this.collapsedRangesState();
    const rangeState = currentState.get(key);

    if (rangeState) {
      const newIsExpanded = !rangeState.isExpanded;

      // Create new map with updated state
      const newState = new Map(currentState);
      newState.set(key, {
        ...rangeState,
        isExpanded: newIsExpanded,
      });

      this.collapsedRangesState.set(newState);

      // Emit toggle event
      this.collapsedRangeToggle.emit({
        range,
        isExpanded: newIsExpanded,
      });
    }
  }

  /**
   * Handler for line widget click events from diff block
   */
  protected onLineWidgetClick(event: LineWidgetClickEvent): void {
    this.lineWidgetClick.emit(event);
  }
}

<article [class]="theme() + ' border-' + borderStyle()">
  <!-- Border overlay for grid-cross style -->
  @if (borderStyle() === 'grid-cross') {
    <div class="border-overlay">
      <div class="border-top"></div>
      <div class="border-bottom"></div>
      <div class="border-left"></div>
      <div class="border-right"></div>
      <div class="corner-cross corner-top-left-h"></div>
      <div class="corner-cross corner-top-left-v"></div>
      <div class="corner-cross corner-top-right-h"></div>
      <div class="corner-cross corner-top-right-v"></div>
      <div class="corner-cross corner-bottom-left-h"></div>
      <div class="corner-cross corner-bottom-left-v"></div>
      <div class="corner-cross corner-bottom-right-h"></div>
      <div class="corner-cross corner-bottom-right-v"></div>
    </div>
  }

  <!-- Border overlay for corner-intersection style -->
  @if (borderStyle() === 'corner-intersection') {
    <div class="border-overlay">
      <div class="border-top-extended"></div>
      <div class="border-bottom-extended"></div>
      <div class="border-left-extended"></div>
      <div class="border-right-extended"></div>
    </div>
  }

  @if (showHeader()) {
    <nx-code-header
      [language]="language()"
      [title]="displayTitle()"
      [theme]="theme()"
      [fileExtension]="fileExtension()" />
  }

  @if (hasChanges()) {
    <div class="diff-stats" [class]="theme()">
      <span class="stat added">+{{ stats().added }}</span>
      <span class="stat removed">-{{ stats().removed }}</span>
    </div>

    <nx-diff-block
      [hunks]="hunks()"
      [theme]="theme()"
      [viewMode]="viewMode()"
      [showLineNumbers]="showLineNumbers()"
      [maxHeight]="maxHeight()"
      [collapsedRangesState]="collapsedRangesState()"
      [lineWidgets]="lineWidgets()"
      (collapsedRangeToggle)="onCollapsedRangeToggle($event)"
      (lineWidgetClick)="onLineWidgetClick($event)" />
  } @else {
    <div class="no-changes" [class]="theme()">No changes to display</div>
  }
</article>

// packages/client/ui/nx-vue-code-viewer/src/lib/organisms/diff-viewer/DiffViewer.vue
<template>
  <div class="nx-diff-viewer">
  <article :class="`${theme} border-${borderStyle}`">
    <div v-if="borderStyle === 'grid-cross'" class="border-overlay">
      <div class="border-top" /><div class="border-bottom" /><div class="border-left" /><div class="border-right" />
      <div class="corner-cross corner-top-left-h" /><div class="corner-cross corner-top-left-v" />
      <div class="corner-cross corner-top-right-h" /><div class="corner-cross corner-top-right-v" />
      <div class="corner-cross corner-bottom-left-h" /><div class="corner-cross corner-bottom-left-v" />
      <div class="corner-cross corner-bottom-right-h" /><div class="corner-cross corner-bottom-right-v" />
    </div>
    <div v-if="borderStyle === 'corner-intersection'" class="border-overlay">
      <div class="border-top-extended" /><div class="border-bottom-extended" /><div class="border-left-extended" /><div class="border-right-extended" />
    </div>

    <CodeHeader
      v-if="showHeader"
      :language="language"
      :title="displayTitle"
      :theme="theme"
      :fileExtension="fileExtension"
    />

    <template v-if="hasChanges">
      <div class="diff-stats" :class="theme">
        <span class="stat added">+{{ stats.added }}</span>
        <span class="stat removed">-{{ stats.removed }}</span>
      </div>

      <DiffBlock
        :hunks="hunks"
        :theme="theme"
        :viewMode="viewMode"
        :showLineNumbers="showLineNumbers"
        :maxHeight="maxHeight"
        :collapsedRangesState="collapsedRangesState"
        :lineWidgets="lineWidgets"
        @collapsed-range-toggle="onCollapsedRangeToggle"
        @line-widget-click="onLineWidgetClick"
      />
    </template>
    <div v-else class="no-changes" :class="theme">No changes to display</div>
  </article>
  </div>
</template>

<script setup lang="ts">
import { ref, computed, watch, onUnmounted } from 'vue';
import {
  DEFAULT_DIFF_VIEWER_CONFIG,
  parseDiff,
  computeDiff,
  getDiffStats,
  parseDiffCollapsedRanges,
  createDiffCollapsedRangesState,
  diffRangeToKey,
  type CodeViewerBorderStyle,
  type CodeViewerLanguage,
  type CodeViewerTheme,
  type DiffCollapsedLinesInput,
  type DiffCollapsedRange,
  type DiffCollapsedRangeState,
  type DiffCollapsedRangeToggleEvent,
  type DiffViewMode,
  type ParsedDiff,
  type ShikiThemeName,
  type ShikiThemePair,
} from '@ngeenx/nx-code-viewer-utils';
import type { VueLineWidgetsInput, VueLineWidgetClickEvent } from '../../types/vue-code-viewer.types';
import { useCodeHighlighter } from '../../composables/useCodeHighlighter';
import { CodeHeader } from '../../atoms/code-header';
import { DiffBlock } from '../../molecules/diff-block';

interface Props {
  diff?: string;
  oldCode?: string;
  newCode?: string;
  viewMode?: DiffViewMode;
  language?: CodeViewerLanguage;
  theme?: CodeViewerTheme;
  shikiTheme?: ShikiThemeName;
  /**
   * Paired Shiki themes for automatic light/dark swapping. Lower
   * precedence than `shikiTheme`; the variant matching the current
   * `theme` is used. Missing slots fall back to `github-dark` /
   * `github-light` defaults.
   */
  shikiThemes?: ShikiThemePair;
  showLineNumbers?: boolean;
  showHeader?: boolean;
  maxHeight?: string;
  oldFileName?: string;
  newFileName?: string;
  fileExtension?: string;
  borderStyle?: CodeViewerBorderStyle;
  collapsedLines?: DiffCollapsedLinesInput;
  lineWidgets?: VueLineWidgetsInput;
}

const props = withDefaults(defineProps<Props>(), {
  diff: '',
  oldCode: '',
  newCode: '',
  viewMode: () => DEFAULT_DIFF_VIEWER_CONFIG.viewMode,
  language: () => DEFAULT_DIFF_VIEWER_CONFIG.language,
  theme: () => DEFAULT_DIFF_VIEWER_CONFIG.theme,
  showLineNumbers: () => DEFAULT_DIFF_VIEWER_CONFIG.showLineNumbers,
  showHeader: () => DEFAULT_DIFF_VIEWER_CONFIG.showHeader,
  maxHeight: '',
  oldFileName: '',
  newFileName: '',
  fileExtension: '',
  borderStyle: 'classic',
  lineWidgets: () => [],
});

const emit = defineEmits<{
  collapsedRangeToggle: [event: DiffCollapsedRangeToggleEvent];
  lineWidgetClick: [event: VueLineWidgetClickEvent];
}>();

const highlighter = useCodeHighlighter();
const parsedDiff = ref<ParsedDiff>({ hunks: [] });
const collapsedRangesState = ref<Map<string, DiffCollapsedRangeState>>(new Map());
let highlightAbortController: AbortController | null = null;

const hunks = computed(() => parsedDiff.value.hunks);
const hasChanges = computed(() => parsedDiff.value.hunks.length > 0);

const displayTitle = computed(() => {
  const newFile = props.newFileName || parsedDiff.value.newFileName;
  const oldFile = props.oldFileName || parsedDiff.value.oldFileName;
  if (newFile && oldFile && newFile !== oldFile) return `${oldFile} → ${newFile}`;
  return newFile || oldFile || '';
});

const stats = computed(() => getDiffStats(parsedDiff.value));

watch(
  [
    () => props.diff,
    () => props.oldCode,
    () => props.newCode,
    () => props.language,
    () => props.theme,
    () => props.shikiTheme,
    () => props.shikiThemes,
  ],
  ([diffValue, oldCode, newCode, language, theme, shikiTheme, shikiThemes]) => {
    void processDiff(diffValue, oldCode, newCode, language, theme, shikiTheme, shikiThemes);
  },
  { immediate: true }
);

watch(
  () => props.collapsedLines,
  (collapsedInput) => {
    const parsedRanges = parseDiffCollapsedRanges(collapsedInput);
    collapsedRangesState.value = createDiffCollapsedRangesState(parsedRanges);
  },
  { immediate: true }
);

onUnmounted(() => {
  abortPendingHighlight();
});

async function processDiff(
  diffValue: string,
  oldCodeValue: string,
  newCodeValue: string,
  language: CodeViewerLanguage,
  theme: CodeViewerTheme,
  shikiTheme?: ShikiThemeName,
  shikiThemes?: ShikiThemePair
): Promise<void> {
  abortPendingHighlight();

  let parsed: ParsedDiff;

  if (diffValue) {
    parsed = parseDiff(diffValue);
  } else if (oldCodeValue || newCodeValue) {
    parsed = computeDiff(oldCodeValue, newCodeValue);
  } else {
    parsedDiff.value = { hunks: [] };
    return;
  }

  parsedDiff.value = parsed;

  if (language === 'plaintext') return;

  highlightAbortController = new AbortController();
  const { signal } = highlightAbortController;

  const oldLines: string[] = [];
  const newLines: string[] = [];

  for (const hunk of parsed.hunks) {
    for (const line of hunk.lines) {
      if (line.type === 'removed' || line.type === 'unchanged') oldLines.push(line.content);
      if (line.type === 'added' || line.type === 'unchanged') newLines.push(line.content);
    }
  }

  const [highlightedOldLines, highlightedNewLines] = await Promise.all([
    highlighter.highlightLines({ code: oldLines.join('\n'), language, theme, signal, shikiTheme, shikiThemes }),
    highlighter.highlightLines({ code: newLines.join('\n'), language, theme, signal, shikiTheme, shikiThemes }),
  ]);

  if (signal.aborted) return;

  parsedDiff.value = {
    ...parsed,
    hunks: applyHighlighting(parsed.hunks, highlightedOldLines, highlightedNewLines),
  };
}

function applyHighlighting(hunks: any[], oldLines: string[], newLines: string[]): any[] {
  let oldIndex = 0;
  let newIndex = 0;

  return hunks.map(hunk => ({
    ...hunk,
    lines: hunk.lines.map((line: any) => {
      let highlightedContent: string | undefined;

      if (line.type === 'removed') highlightedContent = oldLines[oldIndex++];
      else if (line.type === 'added') highlightedContent = newLines[newIndex++];
      else if (line.type === 'unchanged') {
        highlightedContent = oldLines[oldIndex++];
        newIndex++;
      }

      return highlightedContent ? { ...line, highlightedContent } : line;
    }),
  }));
}

function abortPendingHighlight(): void {
  if (highlightAbortController) {
    highlightAbortController.abort();
    highlightAbortController = null;
  }
}

function onCollapsedRangeToggle(range: DiffCollapsedRange): void {
  const key = diffRangeToKey(range);
  const currentState = collapsedRangesState.value;
  const rangeState = currentState.get(key);

  if (rangeState) {
    const newIsExpanded = !rangeState.isExpanded;
    const newState = new Map(currentState);
    newState.set(key, { ...rangeState, isExpanded: newIsExpanded });
    collapsedRangesState.value = newState;
    emit('collapsedRangeToggle', { range, isExpanded: newIsExpanded });
  }
}

function onLineWidgetClick(event: VueLineWidgetClickEvent): void {
  emit('lineWidgetClick', event);
}
</script>
