// apps/vue-demo/src/pages/BorderStylesPage.vue
<template>
  <div class="page-container" :class="{ dark: theme === 'dark', light: theme === 'light' }">
    <header class="page-header">
      <h1 class="page-title">Border Styles</h1>
      <p class="page-description">
        Choose from different border style variants to match your design aesthetic:
        classic, grid-cross, corner-intersection, and none.
      </p>
    </header>

    <section class="demo-section">
      <h2 class="demo-section-title">Available Border Styles</h2>
      <div v-for="borderStyle in borderStyles" :key="borderStyle" class="demo-item">
        <h3 class="demo-item-subtitle">{{ borderStyle }}</h3>
        <CodeViewer
          :code="borderStyleExample.code"
          :language="borderStyleExample.language"
          :theme="theme"
          :shikiTheme="getResolvedShikiTheme()"
          :borderStyle="borderStyle"
          :showHeader="false"
          :showLineNumbers="false"
        />
      </div>
    </section>
  </div>
</template>

<script setup lang="ts">
import { CodeViewer } from '@ngeenx/nx-vue-code-viewer';
import type { CodeViewerBorderStyle, CodeViewerLanguage } from '@ngeenx/nx-vue-code-viewer';
import { useTheme } from '../composables/useTheme';

const { theme, getResolvedShikiTheme } = useTheme();

const borderStyles: CodeViewerBorderStyle[] = [
  'classic',
  'grid-cross',
  'corner-intersection',
  'none',
];

const borderStyleExample = {
  code: `function greet(name: string): string {
  return \`Hello, \${name}!\`;
}

console.log(greet('World'));`,
  language: 'typescript' as CodeViewerLanguage,
};
</script>

// apps/react-demo/src/app/pages/BorderStylesPage.tsx
import { CodeViewer, type CodeViewerBorderStyle } from '@ngeenx/nx-react-code-viewer';
import { useTheme } from '../hooks/useTheme';

const borderStyles: CodeViewerBorderStyle[] = [
  'classic',
  'grid-cross',
  'corner-intersection',
  'none',
];

const borderStyleCode = `function greet(name: string): string {
  return \`Hello, \${name}!\`;
}

console.log(greet('World'));`;

export default function BorderStylesPage() {
  const { theme, getResolvedShikiTheme } = useTheme();

  return (
    <div className={`page-container ${theme}`}>
      <header className="page-header">
        <h1 className="page-title">Border Styles</h1>
        <p className="page-description">
          Choose from different border style variants to match your design aesthetic:
          classic, grid-cross, corner-intersection, and none.
        </p>
      </header>

      <section className="demo-section">
        <h2 className="demo-section-title">Available Border Styles</h2>
        {borderStyles.map((borderStyle) => (
          <div key={borderStyle} className="demo-item">
            <h3 className="demo-item-subtitle">{borderStyle}</h3>
            <CodeViewer
              code={borderStyleCode}
              language="typescript"
              theme={theme}
              shikiTheme={getResolvedShikiTheme()}
              borderStyle={borderStyle}
              showHeader={false}
              showLineNumbers={false}
            />
          </div>
        ))}
      </section>
    </div>
  );
}
