// apps/vue-demo/src/pages/DiffViewerPage.vue
<template>
  <div class="page-container" :class="theme">
    <div class="page-header">
      <h1 class="page-title">Diff Viewer</h1>
      <p class="page-description">
        Compare code changes with unified or split diff views.
      </p>
    </div>

    <div class="demo-section">
      <h2 class="demo-section-title">View Mode</h2>
      <p class="demo-section-description">
        Toggle between unified and split view modes.
      </p>
      <div class="demo-controls">
        <button
          class="demo-toggle-btn"
          :class="{ active: diffViewMode === 'unified' }"
          @click="diffViewMode = 'unified'"
        >
          Unified
        </button>
        <button
          class="demo-toggle-btn"
          :class="{ active: diffViewMode === 'split' }"
          @click="diffViewMode = 'split'"
        >
          Split
        </button>
      </div>
    </div>

    <div class="demo-section" v-for="example in diffExamples" :key="example.title">
      <h2 class="demo-section-title">{{ example.title }}</h2>
      <DiffViewer
        :oldCode="example.oldCode"
        :newCode="example.newCode"
        :language="example.language"
        :theme="theme"
        :shikiTheme="getResolvedShikiTheme()"
        :viewMode="diffViewMode"
        :showLineNumbers="example.showLineNumbers"
        :showHeader="true"
        :oldFileName="example.oldFileName"
        :newFileName="example.newFileName"
        :fileExtension="example.fileExtension"
      />
    </div>

    <div class="demo-section">
      <h2 class="demo-section-title">Long Diff with Fixed Height</h2>
      <p class="demo-section-description">
        A larger diff example with <code>maxHeight="400px"</code> to demonstrate scrollable diff content.
      </p>
      <div class="demo-controls">
        <button
          class="demo-toggle-btn"
          :class="{ active: diffViewMode === 'unified' }"
          @click="diffViewMode = 'unified'"
        >Unified</button>
        <button
          class="demo-toggle-btn"
          :class="{ active: diffViewMode === 'split' }"
          @click="diffViewMode = 'split'"
        >Split</button>
      </div>
      <DiffViewer
        :oldCode="longDiffExample.oldCode"
        :newCode="longDiffExample.newCode"
        :language="longDiffExample.language"
        :theme="theme"
        :shikiTheme="getResolvedShikiTheme()"
        :viewMode="diffViewMode"
        :showLineNumbers="true"
        :showHeader="true"
        maxHeight="400px"
        fileExtension=".ts"
        oldFileName="user.service.ts"
        newFileName="user.service.ts"
      />
    </div>

    <div class="demo-section">
      <h2 class="demo-section-title">Collapsed Lines in Diff</h2>
      <p class="demo-section-description">
        Collapse unchanged regions in diffs to focus on the changes.
      </p>
      <DiffViewer
        :oldCode="diffCollapsedLinesExample.oldCode"
        :newCode="diffCollapsedLinesExample.newCode"
        :language="diffCollapsedLinesExample.language"
        :theme="theme"
        :shikiTheme="getResolvedShikiTheme()"
        :collapsedLines="diffCollapsedLinesExample.collapsedLines"
        :showLineNumbers="true"
        :showHeader="false"
        viewMode="unified"
      />
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue';
import { DiffViewer } from '@ngeenx/nx-vue-code-viewer';
import type { CodeViewerLanguage, DiffViewMode, DiffCollapsedLinesInput } from '@ngeenx/nx-vue-code-viewer';
import { useTheme } from '../composables/useTheme';

const { theme, getResolvedShikiTheme } = useTheme();

const diffViewMode = ref<DiffViewMode>('unified');

const diffExamples: {
  title: string;
  oldCode: string;
  newCode: string;
  language: CodeViewerLanguage;
  fileExtension: string;
  oldFileName: string;
  newFileName: string;
  showLineNumbers: boolean;
}[] = [
  {
    title: 'TypeScript',
    language: 'typescript',
    fileExtension: '.ts',
    oldFileName: 'user.ts',
    newFileName: 'user.ts',
    showLineNumbers: true,
    oldCode: `interface User {
  id: number;
  name: string;
}

function getUser(id: number): User {
  return { id, name: 'John' };
}`,
    newCode: `interface User {
  id: number;
  name: string;
  email: string;
  createdAt: Date;
}

function getUser(id: number): User | null {
  if (id <= 0) return null;
  return {
    id,
    name: 'John',
    email: 'john@example.com',
    createdAt: new Date()
  };
}`,
  },
  {
    title: 'HTML',
    language: 'html',
    fileExtension: '.html',
    oldFileName: 'index.html',
    newFileName: 'index.html',
    showLineNumbers: true,
    oldCode: `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>My App</title>
</head>
<body>
  <header>
    <h1>Welcome</h1>
  </header>
  <main>
    <p>Hello, World!</p>
  </main>
</body>
</html>`,
    newCode: `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>My App - Enhanced</title>
  <link rel="stylesheet" href="styles.css">
</head>
<body>
  <header class="site-header">
    <nav>
      <a href="/">Home</a>
      <a href="/about">About</a>
    </nav>
    <h1>Welcome</h1>
  </header>
  <main class="content">
    <section>
      <p>Hello, World!</p>
      <button id="cta">Get Started</button>
    </section>
  </main>
  <footer>
    <p>&copy; 2024 My App</p>
  </footer>
</body>
</html>`,
  },
  {
    title: 'Plaintext',
    language: 'plaintext',
    fileExtension: '.txt',
    oldFileName: 'notes.txt',
    newFileName: 'notes.txt',
    showLineNumbers: false,
    oldCode: `Project Notes
=============

Current Status:
- Basic implementation complete
- Testing in progress

TODO:
- Fix bug in login module
- Update documentation

Team Members:
- Alice (Lead)
- Bob (Developer)`,
    newCode: `Project Notes
=============

Current Status:
- Basic implementation complete
- Testing completed successfully
- Ready for code review

TODO:
- Update documentation
- Prepare release notes
- Schedule deployment

Team Members:
- Alice (Lead)
- Bob (Developer)
- Charlie (QA)`,
  },
];

const longDiffExample = {
  language: 'typescript' as CodeViewerLanguage,
  oldCode: `import { Injectable } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { Observable } from 'rxjs';

export interface User {
  id: number;
  name: string;
  email: string;
}

export interface CreateUserDto {
  name: string;
  email: string;
}

@Injectable({
  providedIn: 'root',
})
export class UserService {
  private readonly apiUrl = '/api/users';

  constructor(private http: HttpClient) {}

  getUsers(): Observable<User[]> {
    return this.http.get<User[]>(this.apiUrl);
  }

  getUser(id: number): Observable<User> {
    return this.http.get<User>(\`\${this.apiUrl}/\${id}\`);
  }

  createUser(dto: CreateUserDto): Observable<User> {
    return this.http.post<User>(this.apiUrl, dto);
  }

  deleteUser(id: number): Observable<void> {
    return this.http.delete<void>(\`\${this.apiUrl}/\${id}\`);
  }
}`,
  newCode: `import { Injectable, inject } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { Observable, catchError, map, of } from 'rxjs';

export interface User {
  id: number;
  name: string;
  email: string;
  role: 'admin' | 'user' | 'guest';
  createdAt: Date;
  isActive: boolean;
}

export interface CreateUserDto {
  name: string;
  email: string;
  role?: 'admin' | 'user' | 'guest';
}

export interface UpdateUserDto {
  name?: string;
  email?: string;
  role?: 'admin' | 'user' | 'guest';
  isActive?: boolean;
}

export interface PaginatedResponse<T> {
  data: T[];
  total: number;
  page: number;
  pageSize: number;
}

@Injectable({
  providedIn: 'root',
})
export class UserService {
  private readonly apiUrl = '/api/users';
  private readonly http = inject(HttpClient);

  getUsers(page = 1, pageSize = 20): Observable<PaginatedResponse<User>> {
    return this.http.get<PaginatedResponse<User>>(this.apiUrl, {
      params: { page: page.toString(), pageSize: pageSize.toString() },
    });
  }

  getUser(id: number): Observable<User | null> {
    return this.http.get<User>(\`\${this.apiUrl}/\${id}\`).pipe(
      catchError(() => of(null))
    );
  }

  createUser(dto: CreateUserDto): Observable<User> {
    return this.http.post<User>(this.apiUrl, {
      ...dto,
      role: dto.role ?? 'user',
    });
  }

  updateUser(id: number, dto: UpdateUserDto): Observable<User> {
    return this.http.patch<User>(\`\${this.apiUrl}/\${id}\`, dto);
  }

  deleteUser(id: number): Observable<boolean> {
    return this.http.delete(\`\${this.apiUrl}/\${id}\`).pipe(
      map(() => true),
      catchError(() => of(false))
    );
  }

  searchUsers(query: string): Observable<User[]> {
    return this.http.get<User[]>(\`\${this.apiUrl}/search\`, {
      params: { q: query },
    });
  }
}`,
};

const diffCollapsedLinesExample: {
  oldCode: string;
  newCode: string;
  language: CodeViewerLanguage;
  collapsedLines: DiffCollapsedLinesInput;
} = {
  language: 'typescript',
  collapsedLines: [
    { startIndex: 2, endIndex: 5 },
    { startIndex: 10, endIndex: 13 },
  ],
  oldCode: `import { Component } from '@angular/core';

/**
 * UserComponent displays user information.
 * This is a multi-line comment block.
 */
@Component({
  selector: 'app-user',
  template: '<div>{{ name }}</div>',
})
export class UserComponent {
  name = 'John Doe';
  email = 'john@example.com';
}`,
  newCode: `import { Component, signal } from '@angular/core';

/**
 * UserComponent displays user information.
 * This is a multi-line comment block.
 * Updated with signals support.
 */
@Component({
  selector: 'app-user',
  template: '<div>{{ name() }}</div>',
})
export class UserComponent {
  readonly name = signal('John Doe');
  readonly email = signal('john@example.com');
  readonly isActive = signal(true);
}`,
};
</script>

// apps/react-demo/src/app/pages/DiffViewerPage.tsx
import { useState } from 'react';
import { DiffViewer, type DiffViewMode, type CodeViewerBorderStyle, type CodeViewerLanguage, type DiffCollapsedLinesInput } from '@ngeenx/nx-react-code-viewer';
import { useTheme } from '../hooks/useTheme';

const borderStyles: CodeViewerBorderStyle[] = ['classic', 'grid-cross', 'corner-intersection', 'none'];

const diffExamples: {
  title: string;
  oldCode: string;
  newCode: string;
  language: CodeViewerLanguage;
  fileExtension: string;
  oldFileName: string;
  newFileName: string;
  showLineNumbers: boolean;
}[] = [
  {
    title: 'TypeScript',
    language: 'typescript',
    fileExtension: '.ts',
    oldFileName: 'user.ts',
    newFileName: 'user.ts',
    showLineNumbers: true,
    oldCode: `interface User {
  id: number;
  name: string;
}

function getUser(id: number): User {
  return { id, name: 'John' };
}`,
    newCode: `interface User {
  id: number;
  name: string;
  email: string;
  createdAt: Date;
}

function getUser(id: number): User | null {
  if (id <= 0) return null;
  return {
    id,
    name: 'John',
    email: 'john@example.com',
    createdAt: new Date()
  };
}`,
  },
  {
    title: 'HTML',
    language: 'html',
    fileExtension: '.html',
    oldFileName: 'index.html',
    newFileName: 'index.html',
    showLineNumbers: true,
    oldCode: `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>My App</title>
</head>
<body>
  <header>
    <h1>Welcome</h1>
  </header>
  <main>
    <p>Hello, World!</p>
  </main>
</body>
</html>`,
    newCode: `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>My App - Enhanced</title>
  <link rel="stylesheet" href="styles.css">
</head>
<body>
  <header class="site-header">
    <nav>
      <a href="/">Home</a>
      <a href="/about">About</a>
    </nav>
    <h1>Welcome</h1>
  </header>
  <main class="content">
    <section>
      <p>Hello, World!</p>
      <button id="cta">Get Started</button>
    </section>
  </main>
  <footer>
    <p>&copy; 2024 My App</p>
  </footer>
</body>
</html>`,
  },
  {
    title: 'Plaintext',
    language: 'plaintext',
    fileExtension: '.txt',
    oldFileName: 'notes.txt',
    newFileName: 'notes.txt',
    showLineNumbers: false,
    oldCode: `Project Notes
=============

Current Status:
- Basic implementation complete
- Testing in progress

TODO:
- Fix bug in login module
- Update documentation

Team Members:
- Alice (Lead)
- Bob (Developer)`,
    newCode: `Project Notes
=============

Current Status:
- Basic implementation complete
- Testing completed successfully
- Ready for code review

TODO:
- Update documentation
- Prepare release notes
- Schedule deployment

Team Members:
- Alice (Lead)
- Bob (Developer)
- Charlie (QA)`,
  },
];

const longDiffExample = {
  language: 'typescript' as CodeViewerLanguage,
  oldCode: `import { Injectable } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { Observable } from 'rxjs';

export interface User {
  id: number;
  name: string;
  email: string;
}

export interface CreateUserDto {
  name: string;
  email: string;
}

@Injectable({
  providedIn: 'root',
})
export class UserService {
  private readonly apiUrl = '/api/users';

  constructor(private http: HttpClient) {}

  getUsers(): Observable<User[]> {
    return this.http.get<User[]>(this.apiUrl);
  }

  getUser(id: number): Observable<User> {
    return this.http.get<User>(\`\${this.apiUrl}/\${id}\`);
  }

  createUser(dto: CreateUserDto): Observable<User> {
    return this.http.post<User>(this.apiUrl, dto);
  }

  deleteUser(id: number): Observable<void> {
    return this.http.delete<void>(\`\${this.apiUrl}/\${id}\`);
  }
}`,
  newCode: `import { Injectable, inject } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { Observable, catchError, map, of } from 'rxjs';

export interface User {
  id: number;
  name: string;
  email: string;
  role: 'admin' | 'user' | 'guest';
  createdAt: Date;
  isActive: boolean;
}

export interface CreateUserDto {
  name: string;
  email: string;
  role?: 'admin' | 'user' | 'guest';
}

export interface UpdateUserDto {
  name?: string;
  email?: string;
  role?: 'admin' | 'user' | 'guest';
  isActive?: boolean;
}

export interface PaginatedResponse<T> {
  data: T[];
  total: number;
  page: number;
  pageSize: number;
}

@Injectable({
  providedIn: 'root',
})
export class UserService {
  private readonly apiUrl = '/api/users';
  private readonly http = inject(HttpClient);

  getUsers(page = 1, pageSize = 20): Observable<PaginatedResponse<User>> {
    return this.http.get<PaginatedResponse<User>>(this.apiUrl, {
      params: { page: page.toString(), pageSize: pageSize.toString() },
    });
  }

  getUser(id: number): Observable<User | null> {
    return this.http.get<User>(\`\${this.apiUrl}/\${id}\`).pipe(
      catchError(() => of(null))
    );
  }

  createUser(dto: CreateUserDto): Observable<User> {
    return this.http.post<User>(this.apiUrl, {
      ...dto,
      role: dto.role ?? 'user',
    });
  }

  updateUser(id: number, dto: UpdateUserDto): Observable<User> {
    return this.http.patch<User>(\`\${this.apiUrl}/\${id}\`, dto);
  }

  deleteUser(id: number): Observable<boolean> {
    return this.http.delete(\`\${this.apiUrl}/\${id}\`).pipe(
      map(() => true),
      catchError(() => of(false))
    );
  }

  searchUsers(query: string): Observable<User[]> {
    return this.http.get<User[]>(\`\${this.apiUrl}/search\`, {
      params: { q: query },
    });
  }
}`,
};

const diffCollapsedLinesExample: {
  oldCode: string;
  newCode: string;
  language: CodeViewerLanguage;
  collapsedLines: DiffCollapsedLinesInput;
} = {
  language: 'typescript',
  collapsedLines: [
    { startIndex: 2, endIndex: 5 },
    { startIndex: 10, endIndex: 13 },
  ],
  oldCode: `import { Component } from '@angular/core';

/**
 * UserComponent displays user information.
 * This is a multi-line comment block.
 */
@Component({
  selector: 'app-user',
  template: '<div>{{ name }}</div>',
})
export class UserComponent {
  name = 'John Doe';
  email = 'john@example.com';
}`,
  newCode: `import { Component, signal } from '@angular/core';

/**
 * UserComponent displays user information.
 * This is a multi-line comment block.
 * Updated with signals support.
 */
@Component({
  selector: 'app-user',
  template: '<div>{{ name() }}</div>',
})
export class UserComponent {
  readonly name = signal('John Doe');
  readonly email = signal('john@example.com');
  readonly isActive = signal(true);
}`,
};

export default function DiffViewerPage() {
  const { theme, getResolvedShikiTheme } = useTheme();
  const [diffViewMode, setDiffViewMode] = useState<DiffViewMode>('unified');

  const toggleDiffViewMode = () => {
    setDiffViewMode((current) => (current === 'unified' ? 'split' : 'unified'));
  };

  return (
    <div className={`page-container ${theme}`}>
      <header className="page-header">
        <h1 className="page-title">Diff Viewer</h1>
        <p className="page-description">
          Compare code changes with the diff viewer. Supports unified and split view modes,
          different languages, and collapsible sections.
        </p>
      </header>

      <section className="demo-section">
        <h2 className="demo-section-title">Basic Diff Examples</h2>
        <div className="demo-controls">
          <button className="demo-toggle-btn" onClick={toggleDiffViewMode}>
            {diffViewMode === 'unified' ? 'Switch to Split View' : 'Switch to Unified View'}
          </button>
        </div>
        {diffExamples.map((diffExample) => (
          <div key={diffExample.title} className="demo-item">
            <h3 className="demo-item-title">{diffExample.title}</h3>
            <DiffViewer
              oldCode={diffExample.oldCode}
              newCode={diffExample.newCode}
              theme={theme}
              shikiTheme={getResolvedShikiTheme()}
              viewMode={diffViewMode}
              showLineNumbers={diffExample.showLineNumbers}
              showHeader={true}
              language={diffExample.language}
              fileExtension={diffExample.fileExtension}
              oldFileName={diffExample.oldFileName}
              newFileName={diffExample.newFileName}
            />
          </div>
        ))}
      </section>

      <section className="demo-section">
        <h2 className="demo-section-title">Diff with Collapsed Lines</h2>
        <p className="demo-section-description">
          Lines 2-5 and 10-13 (0-based global indices) are collapsed. Click to expand and see the hidden diff lines.
        </p>
        <div className="demo-controls">
          <button className="demo-toggle-btn" onClick={toggleDiffViewMode}>
            {diffViewMode === 'unified' ? 'Switch to Split View' : 'Switch to Unified View'}
          </button>
        </div>
        <DiffViewer
          oldCode={diffCollapsedLinesExample.oldCode}
          newCode={diffCollapsedLinesExample.newCode}
          theme={theme}
          shikiTheme={getResolvedShikiTheme()}
          viewMode={diffViewMode}
          showLineNumbers={true}
          showHeader={true}
          language={diffCollapsedLinesExample.language}
          collapsedLines={diffCollapsedLinesExample.collapsedLines}
          fileExtension=".ts"
          oldFileName="user.component.ts"
          newFileName="user.component.ts"
        />
      </section>

      <section className="demo-section">
        <h2 className="demo-section-title">Long Diff with Fixed Height</h2>
        <p className="demo-section-description">
          A larger diff example with <code>maxHeight="400px"</code> to demonstrate scrollable diff content.
        </p>
        <div className="demo-controls">
          <button className="demo-toggle-btn" onClick={toggleDiffViewMode}>
            {diffViewMode === 'unified' ? 'Switch to Split View' : 'Switch to Unified View'}
          </button>
        </div>
        <DiffViewer
          oldCode={longDiffExample.oldCode}
          newCode={longDiffExample.newCode}
          language={longDiffExample.language}
          theme={theme}
          shikiTheme={getResolvedShikiTheme()}
          viewMode={diffViewMode}
          showLineNumbers={true}
          showHeader={true}
          maxHeight="400px"
          fileExtension=".ts"
          oldFileName="user.service.ts"
          newFileName="user.service.ts"
        />
      </section>

      <section className="demo-section">
        <h2 className="demo-section-title">Diff Viewer Border Styles</h2>
        <p className="demo-section-description">
          Different border style variants for diff viewer.
        </p>
        {borderStyles.map((borderStyle) => (
          <div key={borderStyle} className="demo-item">
            <h3 className="demo-item-subtitle">{borderStyle}</h3>
            <DiffViewer
              oldCode={diffExamples[0].oldCode}
              newCode={diffExamples[0].newCode}
              theme={theme}
              shikiTheme={getResolvedShikiTheme()}
              viewMode="unified"
              showLineNumbers={true}
              showHeader={false}
              language={diffExamples[0].language}
              borderStyle={borderStyle}
            />
          </div>
        ))}
      </section>
    </div>
  );
}
