// packages/client/ui/nx-angular-code-viewer/src/lib/atoms/tab-header/tab-header.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  computed,
  input,
  output,
} from '@angular/core';
import { getFileIconUrl, type CodeViewerTheme } from '@ngeenx/nx-code-viewer-utils';

/**
 * TabHeader Atom Component
 *
 * Renders a single tab header with file icon, name, and active state.
 * Used within TabBarComponent for tab navigation.
 *
 * @example
 * ```html
 * <nx-tab-header
 *   tabId="file-1"
 *   fileName="app.component.ts"
 *   fileExtension=".ts"
 *   [isActive]="true"
 *   [theme]="'dark'"
 *   (tabClick)="onTabClick($event)"
 * />
 * ```
 */
@Component({
  selector: 'nx-tab-header',
  imports: [],
  templateUrl: './tab-header.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { class: 'nx-tab-header' },
})
export class TabHeaderComponent {
  /**
   * Unique identifier for the tab
   */
  readonly tabId = input.required<string>();

  /**
   * Display name for the tab
   */
  readonly fileName = input.required<string>();

  /**
   * File extension for icon display
   */
  readonly fileExtension = input<string>('');

  /**
   * Whether this tab is currently active
   */
  readonly isActive = input<boolean>(false);

  /**
   * Theme for styling
   */
  readonly theme = input<CodeViewerTheme>('dark');

  /**
   * Emits when the tab is clicked
   */
  readonly tabClick = output<string>();

  /**
   * Emits when keyboard navigation occurs
   */
  readonly tabKeydown = output<KeyboardEvent>();

  /**
   * Computed icon URL from file extension
   */
  protected readonly iconUrl = computed(() => {
    const ext = this.fileExtension();
    return ext ? getFileIconUrl(ext) : null;
  });

  /**
   * Handle click events
   */
  protected onClick(): void {
    this.tabClick.emit(this.tabId());
  }

  /**
   * Handle keyboard events
   */
  protected onKeydown(event: KeyboardEvent): void {
    this.tabKeydown.emit(event);
  }
}

<button
  type="button"
  role="tab"
  [attr.aria-selected]="isActive()"
  [attr.aria-controls]="'panel-' + tabId()"
  [attr.id]="'tab-' + tabId()"
  [attr.tabindex]="isActive() ? 0 : -1"
  [class]="theme()"
  [class.active]="isActive()"
  (click)="onClick()"
  (keydown)="onKeydown($event)">
  @if (iconUrl()) {
    <img [src]="iconUrl()" class="file-icon" [alt]="fileName()" />
  }
  <span class="file-name">{{ fileName() }}</span>
</button>

// packages/client/ui/nx-vue-code-viewer/src/lib/atoms/tab-header/TabHeader.vue
<template>
  <div class="nx-tab-header">
    <button
      type="button"
      role="tab"
      :aria-selected="isActive"
      :aria-controls="`panel-${tabId}`"
      :id="`tab-${tabId}`"
      :tabindex="isActive ? 0 : -1"
      :class="[theme, { active: isActive }]"
      @click="onClick"
      @keydown="onKeydown"
    >
      <img v-if="iconUrl" :src="iconUrl" class="file-icon" :alt="fileName" />
      <span class="file-name">{{ fileName }}</span>
    </button>
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue';
import { getFileIconUrl, type CodeViewerTheme } from '@ngeenx/nx-code-viewer-utils';

interface Props {
  tabId: string;
  fileName: string;
  fileExtension?: string;
  isActive?: boolean;
  theme?: CodeViewerTheme;
}

const props = withDefaults(defineProps<Props>(), {
  fileExtension: '',
  isActive: false,
  theme: 'dark',
});

const emit = defineEmits<{
  tabClick: [tabId: string];
  tabKeydown: [event: KeyboardEvent];
}>();

const iconUrl = computed<string | null>(() => {
  return props.fileExtension ? getFileIconUrl(props.fileExtension) : null;
});

function onClick(): void {
  emit('tabClick', props.tabId);
}

function onKeydown(event: KeyboardEvent): void {
  emit('tabKeydown', event);
}
</script>
