// apps/angular-demo/src/app/pages/border-styles/border-styles.page.ts
import { Component, inject } from '@angular/core';
import {
  CodeViewerComponent,
  CodeViewerBorderStyle,
  CodeViewerLanguage,
} from '@ngeenx/nx-angular-code-viewer';
import { ThemeService } from '../../services/theme.service';

@Component({
  selector: 'app-border-styles',
  imports: [CodeViewerComponent],
  templateUrl: './border-styles.page.html',
  styleUrls: ['../page.css'],
})
export class BorderStylesPage {
  protected readonly themeService = inject(ThemeService);
  protected readonly theme = this.themeService.theme;
  protected readonly shikiTheme = this.themeService.getResolvedShikiTheme.bind(
    this.themeService
  );

  protected readonly borderStyles: CodeViewerBorderStyle[] = [
    'classic',
    'grid-cross',
    'corner-intersection',
    'none',
  ];

  protected readonly borderStyleExample = {
    code: `function greet(name: string): string {
  return \`Hello, \${name}!\`;
}

console.log(greet('World'));`,
    language: 'typescript' as CodeViewerLanguage,
  };
}

// apps/vue-demo/src/pages/BorderStylesPage.vue
<template>
  <div class="page-container" :class="{ dark: theme === 'dark', light: theme === 'light' }">
    <header class="page-header">
      <h1 class="page-title">Border Styles</h1>
      <p class="page-description">
        Choose from different border style variants to match your design aesthetic:
        classic, grid-cross, corner-intersection, and none.
      </p>
    </header>

    <section class="demo-section">
      <h2 class="demo-section-title">Available Border Styles</h2>
      <div v-for="borderStyle in borderStyles" :key="borderStyle" class="demo-item">
        <h3 class="demo-item-subtitle">{{ borderStyle }}</h3>
        <CodeViewer
          :code="borderStyleExample.code"
          :language="borderStyleExample.language"
          :theme="theme"
          :shikiTheme="getResolvedShikiTheme()"
          :borderStyle="borderStyle"
          :showHeader="false"
          :showLineNumbers="false"
        />
      </div>
    </section>
  </div>
</template>

<script setup lang="ts">
import { CodeViewer } from '@ngeenx/nx-vue-code-viewer';
import type { CodeViewerBorderStyle, CodeViewerLanguage } from '@ngeenx/nx-vue-code-viewer';
import { useTheme } from '../composables/useTheme';

const { theme, getResolvedShikiTheme } = useTheme();

const borderStyles: CodeViewerBorderStyle[] = [
  'classic',
  'grid-cross',
  'corner-intersection',
  'none',
];

const borderStyleExample = {
  code: `function greet(name: string): string {
  return \`Hello, \${name}!\`;
}

console.log(greet('World'));`,
  language: 'typescript' as CodeViewerLanguage,
};
</script>
