// packages/client/ui/nx-angular-code-viewer/src/lib/molecules/diff-block/diff-block.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  computed,
  input,
  output,
  signal,
} from '@angular/core';
import { NgStyle } from '@angular/common';
import {
  toSplitViewLines,
  isDiffLineInCollapsedRange,
  type CodeViewerTheme,
  type DiffCollapsedLinesInput,
  type DiffCollapsedRange,
  type DiffCollapsedRangeState,
  type DiffHunk,
  type DiffLine,
  type DiffViewMode,
  type LineWidgetClickEvent,
  type LineWidgetConfig,
  type LineWidgetContext,
  type LineWidgetsInput,
  type SplitViewLine,
} from '@ngeenx/nx-code-viewer-utils';
import { DiffLineComponent } from '../../atoms/diff-line';
import { DiffCollapsedIndicatorComponent } from '../../atoms/diff-collapsed-indicator';
import { InsertWidgetContainerComponent } from '../../atoms/insert-widget-container';

/**
 * DiffBlock Molecule Component
 *
 * Renders diff hunks in either unified or split view mode.
 *
 * @example
 * ```html
 * <nx-diff-block
 *   [hunks]="parsedDiff.hunks"
 *   [theme]="'dark'"
 *   [viewMode]="'unified'"
 *   [showLineNumbers]="true"
 * />
 * ```
 */
@Component({
  selector: 'nx-diff-block',
  imports: [
    NgStyle,
    DiffLineComponent,
    DiffCollapsedIndicatorComponent,
    InsertWidgetContainerComponent,
  ],
  templateUrl: './diff-block.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { class: 'nx-diff-block' },
})
export class DiffBlockComponent {
  /**
   * Diff hunks to display
   */
  readonly hunks = input.required<readonly DiffHunk[]>();

  /**
   * Theme for styling
   */
  readonly theme = input<CodeViewerTheme>('dark');

  /**
   * View mode: unified or split
   */
  readonly viewMode = input<DiffViewMode>('unified');

  /**
   * Whether to show line numbers
   */
  readonly showLineNumbers = input<boolean>(true);

  /**
   * Maximum height with scroll
   */
  readonly maxHeight = input<string>('');

  /**
   * Map of collapsed range states
   */
  readonly collapsedRangesState = input<Map<string, DiffCollapsedRangeState>>(
    new Map()
  );

  /**
   * Emitted when a collapsed range indicator is clicked
   */
  readonly collapsedRangeToggle = output<DiffCollapsedRange>();

  /**
   * Line widget configurations
   */
  readonly lineWidgets = input<LineWidgetsInput>();

  /**
   * Emits when a line widget is clicked
   */
  readonly lineWidgetClick = output<LineWidgetClickEvent>();

  /**
   * Currently active insert widget (for showing component between lines)
   */
  protected readonly activeInsertWidget = signal<{
    lineNumber: number;
    widget: LineWidgetConfig;
    line: string;
  } | null>(null);

  /**
   * Computed container styles for max height
   */
  protected readonly containerStyle = computed(() => {
    const height = this.maxHeight();
    return height ? { 'max-height': height } : {};
  });

  /**
   * Whether we're in unified view mode
   */
  protected readonly isUnifiedView = computed(
    () => this.viewMode() === 'unified'
  );

  /**
   * Flattened unified view data with global line indices
   */
  protected readonly unifiedViewData = computed(() => {
    const result: {
      header: string;
      lines: { line: DiffLine; globalIndex: number }[];
    }[] = [];
    let globalIndex = 0;

    for (const hunk of this.hunks()) {
      const lines: { line: DiffLine; globalIndex: number }[] = [];
      for (const line of hunk.lines) {
        lines.push({ line, globalIndex });
        globalIndex++;
      }
      result.push({ header: hunk.header, lines });
    }

    return result;
  });

  /**
   * Split view lines for each hunk (computed for split mode)
   */
  protected readonly splitViewHunks = computed(() => {
    let globalIndex = 0;
    return this.hunks().map(hunk => {
      const lines = toSplitViewLines(hunk.lines).map(pair => {
        const result = { ...pair, globalIndex };
        globalIndex++;
        return result;
      });
      return { header: hunk.header, lines };
    });
  });

  /**
   * Currently hovered line index (-1 = none)
   */
  protected readonly hoveredLineIndex = signal<number>(-1);

  /**
   * Track function for hunks
   */
  protected trackHunk(_index: number, hunk: DiffHunk): string {
    return hunk.header;
  }

  /**
   * Track function for split view lines
   */
  protected trackSplitLine(index: number, _line: SplitViewLine): number {
    return index;
  }

  /**
   * Handle line hover event
   */
  protected onLineHover(lineIndex: number): void {
    this.hoveredLineIndex.set(lineIndex);
  }

  /**
   * Clear hover state on mouse leave
   */
  protected onMouseLeave(): void {
    this.hoveredLineIndex.set(-1);
  }

  /**
   * Check if a line is in a collapsed range
   */
  protected getLineCollapseInfo(globalIndex: number): {
    isCollapsed: boolean;
    isFirstLine: boolean;
    range: DiffCollapsedRange | null;
    hiddenCount: number;
  } {
    return isDiffLineInCollapsedRange(globalIndex, this.collapsedRangesState());
  }

  /**
   * Check if a line should be visible
   */
  protected isLineVisible(globalIndex: number): boolean {
    const collapseInfo = this.getLineCollapseInfo(globalIndex);
    return !collapseInfo.isCollapsed || collapseInfo.isFirstLine;
  }

  /**
   * Handle collapsed range toggle
   */
  protected onCollapsedRangeToggle(range: DiffCollapsedRange): void {
    this.collapsedRangeToggle.emit(range);
  }

  /**
   * Handle line widget click
   */
  protected onLineWidgetClick(event: LineWidgetClickEvent, line: DiffLine): void {
    this.lineWidgetClick.emit(event);

    // Toggle insert widget if the widget has an insertComponent
    if (event.widget.insertComponent) {
      const current = this.activeInsertWidget();

      if (current?.lineNumber === event.lineNumber && current.widget === event.widget) {
        // Clicking same widget again closes it
        this.activeInsertWidget.set(null);
      } else {
        // Open new insert widget
        this.activeInsertWidget.set({
          lineNumber: event.lineNumber,
          widget: event.widget,
          line: line.content,
        });
      }
    }
  }

  /**
   * Check if insert widget should be shown after a specific line
   */
  protected shouldShowInsertWidget(lineNumber: number): boolean {
    const active = this.activeInsertWidget();
    return active !== null && active.lineNumber === lineNumber;
  }

  /**
   * Get context for the active insert widget
   */
  protected getInsertWidgetContext(): LineWidgetContext {
    const active = this.activeInsertWidget();
    return {
      line: active?.line ?? '',
      lineNumber: active?.lineNumber ?? 0,
      theme: this.theme(),
    };
  }
}

<div
  class="diff-block-container"
  [class]="theme()"
  [ngStyle]="containerStyle()"
  (mouseleave)="onMouseLeave()">
  @if (isUnifiedView()) {
    <!-- Unified View -->
    @for (hunk of unifiedViewData(); track hunk.header) {
      <div class="hunk">
        <div class="hunk-header">{{ hunk.header }}</div>
        @for (item of hunk.lines; track item.globalIndex) {
          @let collapseInfo = getLineCollapseInfo(item.globalIndex);

          @if (isLineVisible(item.globalIndex)) {
            @let lineNum = item.line.newLineNumber ?? item.line.oldLineNumber ?? 0;

            <nx-diff-line
              [line]="item.line"
              [theme]="theme()"
              [showLineNumbers]="showLineNumbers()"
              [showPrefix]="true"
              [lineIndex]="item.globalIndex"
              [isHighlighted]="hoveredLineIndex() === item.globalIndex"
              [lineWidgets]="lineWidgets()"
              (lineHover)="onLineHover($event)"
              (lineWidgetClick)="onLineWidgetClick($event, item.line)" />

            <!-- Show insert widget if active for this line -->
            @if (shouldShowInsertWidget(lineNum) && activeInsertWidget()) {
              <nx-insert-widget-container
                [component]="activeInsertWidget()!.widget.insertComponent!"
                [context]="getInsertWidgetContext()"
                [theme]="theme()" />
            }

            <!-- Show collapse indicator after first line of collapsed range -->
            @if (collapseInfo.isFirstLine && collapseInfo.range) {
              <nx-diff-collapsed-indicator
                [theme]="theme()"
                [range]="collapseInfo.range"
                [hiddenCount]="collapseInfo.hiddenCount"
                [showLineNumbers]="showLineNumbers()"
                [showPrefix]="true"
                (toggle)="onCollapsedRangeToggle(collapseInfo.range)" />
            }
          }
        }
      </div>
    }
  } @else {
    <!-- Split View -->
    @for (hunk of splitViewHunks(); track $index) {
      <div class="hunk">
        <div class="hunk-header">{{ hunk.header }}</div>
        <div class="split-container">
          <div class="split-pane left">
            @for (pair of hunk.lines; track pair.globalIndex) {
              @let collapseInfo = getLineCollapseInfo(pair.globalIndex);

              @if (isLineVisible(pair.globalIndex)) {
                @if (pair.left) {
                  @let leftLineNum = pair.left.oldLineNumber ?? 0;

                  <nx-diff-line
                    [line]="pair.left"
                    [theme]="theme()"
                    [showLineNumbers]="showLineNumbers()"
                    [showPrefix]="false"
                    [lineIndex]="pair.globalIndex"
                    [isHighlighted]="hoveredLineIndex() === pair.globalIndex"
                    [lineWidgets]="lineWidgets()"
                    (lineHover)="onLineHover($event)"
                    (lineWidgetClick)="onLineWidgetClick($event, pair.left)" />

                  <!-- Show insert widget if active for this line -->
                  @if (shouldShowInsertWidget(leftLineNum) && activeInsertWidget()) {
                    <nx-insert-widget-container
                      [component]="activeInsertWidget()!.widget.insertComponent!"
                      [context]="getInsertWidgetContext()"
                      [theme]="theme()" />
                  }
                } @else {
                  <div class="empty-line"></div>
                }

                @if (collapseInfo.isFirstLine && collapseInfo.range) {
                  <nx-diff-collapsed-indicator
                    [theme]="theme()"
                    [range]="collapseInfo.range"
                    [hiddenCount]="collapseInfo.hiddenCount"
                    [showLineNumbers]="showLineNumbers()"
                    [showPrefix]="false"
                    (toggle)="onCollapsedRangeToggle(collapseInfo.range)" />
                }
              }
            }
          </div>
          <div class="split-pane right">
            @for (pair of hunk.lines; track pair.globalIndex) {
              @let collapseInfo = getLineCollapseInfo(pair.globalIndex);

              @if (isLineVisible(pair.globalIndex)) {
                @if (pair.right) {
                  @let rightLineNum = pair.right.newLineNumber ?? 0;

                  <nx-diff-line
                    [line]="pair.right"
                    [theme]="theme()"
                    [showLineNumbers]="showLineNumbers()"
                    [showPrefix]="false"
                    [lineIndex]="pair.globalIndex"
                    [isHighlighted]="hoveredLineIndex() === pair.globalIndex"
                    [lineWidgets]="lineWidgets()"
                    (lineHover)="onLineHover($event)"
                    (lineWidgetClick)="onLineWidgetClick($event, pair.right)" />

                  <!-- Show insert widget if active for this line -->
                  @if (shouldShowInsertWidget(rightLineNum) && activeInsertWidget()) {
                    <nx-insert-widget-container
                      [component]="activeInsertWidget()!.widget.insertComponent!"
                      [context]="getInsertWidgetContext()"
                      [theme]="theme()" />
                  }
                } @else {
                  <div class="empty-line"></div>
                }

                @if (collapseInfo.isFirstLine && collapseInfo.range) {
                  <nx-diff-collapsed-indicator
                    [theme]="theme()"
                    [range]="collapseInfo.range"
                    [hiddenCount]="collapseInfo.hiddenCount"
                    [showLineNumbers]="showLineNumbers()"
                    [showPrefix]="false"
                    (toggle)="onCollapsedRangeToggle(collapseInfo.range)" />
                }
              }
            }
          </div>
        </div>
      </div>
    }
  }
</div>

// packages/client/ui/nx-vue-code-viewer/src/lib/molecules/diff-block/DiffBlock.vue
<template>
  <div
    class="diff-block-container"
    :class="theme"
    :style="containerStyle"
    @mouseleave="onMouseLeave"
  >
    <!-- Unified View -->
    <template v-if="isUnifiedView">
      <div v-for="hunk in unifiedViewData" :key="hunk.header" class="hunk">
        <div class="hunk-header">{{ hunk.header }}</div>
        <template v-for="item in hunk.lines" :key="item.globalIndex">
          <template v-if="isLineVisible(item.globalIndex)">
            <DiffLine
              :line="item.line"
              :theme="theme"
              :showLineNumbers="showLineNumbers"
              :showPrefix="true"
              :lineIndex="item.globalIndex"
              :isHighlighted="hoveredLineIndex === item.globalIndex"
              :lineWidgets="lineWidgets"
              @line-hover="onLineHover"
              @line-widget-click="(e) => onLineWidgetClick(e, item.line)"
            />

            <component
              v-if="shouldShowInsertWidget(item.line.newLineNumber ?? item.line.oldLineNumber ?? 0) && activeInsertWidget?.widget.insertComponent"
              :is="activeInsertWidget.widget.insertComponent"
              v-bind="getInsertWidgetContext()"
              @close="activeInsertWidget = null"
            />

            <DiffCollapsedIndicator
              v-if="getLineCollapseInfo(item.globalIndex).isFirstLine && getLineCollapseInfo(item.globalIndex).range"
              :theme="theme"
              :range="getLineCollapseInfo(item.globalIndex).range!"
              :hiddenCount="getLineCollapseInfo(item.globalIndex).hiddenCount"
              :showLineNumbers="showLineNumbers"
              :showPrefix="true"
              @toggle="onCollapsedRangeToggle(getLineCollapseInfo(item.globalIndex).range!)"
            />
          </template>
        </template>
      </div>
    </template>

    <!-- Split View -->
    <template v-else>
      <div v-for="(hunk, hi) in splitViewHunks" :key="hi" class="hunk">
        <div class="hunk-header">{{ hunk.header }}</div>
        <div class="split-container">
          <div class="split-pane left">
            <template v-for="pair in hunk.lines" :key="pair.globalIndex">
              <template v-if="isLineVisible(pair.globalIndex)">
                <template v-if="pair.left">
                  <DiffLine
                    :line="pair.left"
                    :theme="theme"
                    :showLineNumbers="showLineNumbers"
                    :showPrefix="false"
                    :lineIndex="pair.globalIndex"
                    :isHighlighted="hoveredLineIndex === pair.globalIndex"
                    :lineWidgets="lineWidgets"
                    @line-hover="onLineHover"
                    @line-widget-click="(e) => onLineWidgetClick(e, pair.left!)"
                  />

                  <component
                    v-if="shouldShowInsertWidget(pair.left.oldLineNumber ?? 0) && activeInsertWidget?.widget.insertComponent"
                    :is="activeInsertWidget.widget.insertComponent"
                    v-bind="getInsertWidgetContext()"
                    @close="activeInsertWidget = null"
                  />
                </template>
                <div v-else class="empty-line" />

                <DiffCollapsedIndicator
                  v-if="getLineCollapseInfo(pair.globalIndex).isFirstLine && getLineCollapseInfo(pair.globalIndex).range"
                  :theme="theme"
                  :range="getLineCollapseInfo(pair.globalIndex).range!"
                  :hiddenCount="getLineCollapseInfo(pair.globalIndex).hiddenCount"
                  :showLineNumbers="showLineNumbers"
                  :showPrefix="false"
                  @toggle="onCollapsedRangeToggle(getLineCollapseInfo(pair.globalIndex).range!)"
                />
              </template>
            </template>
          </div>
          <div class="split-pane right">
            <template v-for="pair in hunk.lines" :key="pair.globalIndex">
              <template v-if="isLineVisible(pair.globalIndex)">
                <template v-if="pair.right">
                  <DiffLine
                    :line="pair.right"
                    :theme="theme"
                    :showLineNumbers="showLineNumbers"
                    :showPrefix="false"
                    :lineIndex="pair.globalIndex"
                    :isHighlighted="hoveredLineIndex === pair.globalIndex"
                    :lineWidgets="lineWidgets"
                    @line-hover="onLineHover"
                    @line-widget-click="(e) => onLineWidgetClick(e, pair.right!)"
                  />

                  <component
                    v-if="shouldShowInsertWidget(pair.right.newLineNumber ?? 0) && activeInsertWidget?.widget.insertComponent"
                    :is="activeInsertWidget.widget.insertComponent"
                    v-bind="getInsertWidgetContext()"
                    @close="activeInsertWidget = null"
                  />
                </template>
                <div v-else class="empty-line" />

                <DiffCollapsedIndicator
                  v-if="getLineCollapseInfo(pair.globalIndex).isFirstLine && getLineCollapseInfo(pair.globalIndex).range"
                  :theme="theme"
                  :range="getLineCollapseInfo(pair.globalIndex).range!"
                  :hiddenCount="getLineCollapseInfo(pair.globalIndex).hiddenCount"
                  :showLineNumbers="showLineNumbers"
                  :showPrefix="false"
                  @toggle="onCollapsedRangeToggle(getLineCollapseInfo(pair.globalIndex).range!)"
                />
              </template>
            </template>
          </div>
        </div>
      </div>
    </template>
  </div>
</template>

<script setup lang="ts">
import { ref, computed } from 'vue';
import {
  toSplitViewLines,
  isDiffLineInCollapsedRange,
  type CodeViewerTheme,
  type DiffCollapsedRange,
  type DiffCollapsedRangeState,
  type DiffHunk,
  type DiffLine as DiffLineType,
  type DiffViewMode,
  type LineWidgetContext,
} from '@ngeenx/nx-code-viewer-utils';
import type { VueLineWidgetsInput, VueLineWidgetConfig, VueLineWidgetClickEvent } from '../../types/vue-code-viewer.types';
import { DiffLine } from '../../atoms/diff-line';
import { DiffCollapsedIndicator } from '../../atoms/diff-collapsed-indicator';

interface Props {
  hunks: readonly DiffHunk[];
  theme?: CodeViewerTheme;
  viewMode?: DiffViewMode;
  showLineNumbers?: boolean;
  maxHeight?: string;
  collapsedRangesState?: Map<string, DiffCollapsedRangeState>;
  lineWidgets?: VueLineWidgetsInput;
}

const props = withDefaults(defineProps<Props>(), {
  theme: 'dark',
  viewMode: 'unified',
  showLineNumbers: true,
  maxHeight: '',
  collapsedRangesState: () => new Map(),
  lineWidgets: () => [],
});

const emit = defineEmits<{
  collapsedRangeToggle: [range: DiffCollapsedRange];
  lineWidgetClick: [event: VueLineWidgetClickEvent];
}>();

const hoveredLineIndex = ref<number>(-1);
const activeInsertWidget = ref<{ lineNumber: number; widget: VueLineWidgetConfig; line: string } | null>(null);

const containerStyle = computed(() => props.maxHeight ? { 'max-height': props.maxHeight } : {});
const isUnifiedView = computed(() => props.viewMode === 'unified');

const unifiedViewData = computed(() => {
  const result: { header: string; lines: { line: DiffLineType; globalIndex: number }[] }[] = [];
  let globalIndex = 0;

  for (const hunk of props.hunks) {
    const lines: { line: DiffLineType; globalIndex: number }[] = [];
    for (const line of hunk.lines) {
      lines.push({ line, globalIndex });
      globalIndex++;
    }
    result.push({ header: hunk.header, lines });
  }

  return result;
});

const splitViewHunks = computed(() => {
  let globalIndex = 0;
  return props.hunks.map(hunk => {
    const lines = toSplitViewLines(hunk.lines).map(pair => {
      const result = { ...pair, globalIndex };
      globalIndex++;
      return result;
    });
    return { header: hunk.header, lines };
  });
});

function getLineCollapseInfo(globalIndex: number) {
  return isDiffLineInCollapsedRange(globalIndex, props.collapsedRangesState);
}

function isLineVisible(globalIndex: number): boolean {
  const info = getLineCollapseInfo(globalIndex);
  return !info.isCollapsed || info.isFirstLine;
}

function onLineHover(lineIndex: number): void {
  hoveredLineIndex.value = lineIndex;
}

function onMouseLeave(): void {
  hoveredLineIndex.value = -1;
}

function onCollapsedRangeToggle(range: DiffCollapsedRange): void {
  emit('collapsedRangeToggle', range);
}

function onLineWidgetClick(event: VueLineWidgetClickEvent, line: DiffLineType): void {
  emit('lineWidgetClick', event);

  if (event.widget.insertComponent) {
    const current = activeInsertWidget.value;
    if (current?.lineNumber === event.lineNumber && current.widget === event.widget) {
      activeInsertWidget.value = null;
    } else {
      activeInsertWidget.value = { lineNumber: event.lineNumber, widget: event.widget, line: line.content };
    }
  }
}

function shouldShowInsertWidget(lineNumber: number): boolean {
  return activeInsertWidget.value !== null && activeInsertWidget.value.lineNumber === lineNumber;
}

function getInsertWidgetContext(): LineWidgetContext {
  const active = activeInsertWidget.value;
  return {
    line: active?.line ?? '',
    lineNumber: active?.lineNumber ?? 0,
    theme: props.theme,
  };
}
</script>
