// packages/client/ui/nx-react-code-viewer/src/lib/atoms/copy-button/CopyButton.tsx
import { memo, useMemo } from 'react';
import type { CopyButtonState, CodeViewerTheme } from '@ngeenx/nx-code-viewer-utils';

interface CopyButtonProps {
  state?: CopyButtonState;
  theme?: CodeViewerTheme;
  disabled?: boolean;
  onCopyClick?: () => void;
}

const CopyIcon = () => (
  <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
    <rect width="14" height="14" x="8" y="8" rx="2" ry="2" />
    <path d="M4 16c-1.1 0-2-.9-2-2V4c0-1.1.9-2 2-2h10c1.1 0 2 .9 2 2" />
  </svg>
);

const CheckIcon = () => (
  <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
    <path d="M20 6 9 17l-5-5" />
  </svg>
);

const XIcon = () => (
  <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
    <path d="M18 6 6 18" />
    <path d="m6 6 12 12" />
  </svg>
);

export const CopyButton = memo(function CopyButton({
  state = 'idle',
  theme = 'dark',
  disabled = false,
  onCopyClick,
}: CopyButtonProps) {
  const icon = useMemo(() => {
    switch (state) {
      case 'copied': return <CheckIcon />;
      case 'error': return <XIcon />;
      default: return <CopyIcon />;
    }
  }, [state]);

  const buttonClasses = useMemo(() => {
    const classes: string[] = [theme];
    if (state !== 'idle') classes.push(state);
    return classes.join(' ');
  }, [theme, state]);

  const ariaLabel = useMemo(() => {
    switch (state) {
      case 'copied': return 'Copied to clipboard';
      case 'error': return 'Failed to copy';
      default: return 'Copy to clipboard';
    }
  }, [state]);

  return (
    <div className="nx-copy-button">
      <button
        type="button"
        className={buttonClasses}
        disabled={disabled}
        aria-label={ariaLabel}
        onClick={() => !disabled && onCopyClick?.()}
      >
        {icon}
      </button>
    </div>
  );
});

// packages/client/ui/nx-vue-code-viewer/src/lib/atoms/copy-button/CopyButton.vue
<template>
  <span class="nx-copy-button">
  <button
    type="button"
    :class="buttonClasses"
    :disabled="disabled"
    :aria-label="ariaLabel"
    @click="onClick"
  >
    <svg
      v-if="state === 'copied'"
      viewBox="0 0 24 24"
      width="16"
      height="16"
      fill="none"
      stroke="currentColor"
      stroke-width="2"
      stroke-linecap="round"
      stroke-linejoin="round"
      aria-hidden="true"
    >
      <polyline points="20 6 9 17 4 12" />
    </svg>
    <svg
      v-else-if="state === 'error'"
      viewBox="0 0 24 24"
      width="16"
      height="16"
      fill="none"
      stroke="currentColor"
      stroke-width="2"
      stroke-linecap="round"
      stroke-linejoin="round"
      aria-hidden="true"
    >
      <line x1="18" y1="6" x2="6" y2="18" />
      <line x1="6" y1="6" x2="18" y2="18" />
    </svg>
    <svg
      v-else
      viewBox="0 0 24 24"
      width="16"
      height="16"
      fill="none"
      stroke="currentColor"
      stroke-width="2"
      stroke-linecap="round"
      stroke-linejoin="round"
      aria-hidden="true"
    >
      <rect x="9" y="9" width="13" height="13" rx="2" ry="2" />
      <path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1" />
    </svg>
  </button>
  </span>
</template>

<script setup lang="ts">
import { computed } from 'vue';
import type { CopyButtonState, CodeViewerTheme } from '@ngeenx/nx-code-viewer-utils';

interface Props {
  state?: CopyButtonState;
  theme?: CodeViewerTheme;
  disabled?: boolean;
}

const props = withDefaults(defineProps<Props>(), {
  state: 'idle',
  theme: 'dark',
  disabled: false,
});

const emit = defineEmits<{
  copyClick: [];
}>();

const buttonClasses = computed(() => {
  const classes = [props.theme];
  if (props.state !== 'idle') classes.push(props.state);
  return classes.join(' ');
});

const ariaLabel = computed(() => {
  switch (props.state) {
    case 'copied': return 'Copied to clipboard';
    case 'error': return 'Failed to copy';
    default: return 'Copy to clipboard';
  }
});

function onClick(): void {
  if (!props.disabled) {
    emit('copyClick');
  }
}
</script>
