// packages/client/ui/nx-angular-code-viewer/src/lib/atoms/diff-line/diff-line.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  computed,
  inject,
  input,
  output,
} from '@angular/core';
import { DomSanitizer, type SafeHtml } from '@angular/platform-browser';
import type { CodeViewerTheme, DiffLine } from '@ngeenx/nx-code-viewer-utils';
import type {
  LineWidgetClickEvent,
  LineWidgetConfig,
  LineWidgetContext,
  LineWidgetsInput,
} from '../../types/line-widget.types';
import { getDiffLinePrefix } from '@ngeenx/nx-code-viewer-utils';
import { getMatchingWidgets } from '../../utils/line-widget.utils';
import { LineWidgetHostComponent } from '../line-widget-host';

/**
 * DiffLine Atom Component
 *
 * Displays a single line of a diff with appropriate styling based on the line type.
 *
 * @example
 * ```html
 * <nx-diff-line
 *   [line]="diffLine"
 *   [theme]="'dark'"
 *   [showLineNumbers]="true"
 *   [showPrefix]="true"
 * />
 * ```
 */
@Component({
  selector: 'nx-diff-line',
  standalone: true,
  imports: [LineWidgetHostComponent],
  templateUrl: './diff-line.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { class: 'nx-diff-line' },
})
export class DiffLineComponent {
  private readonly sanitizer = inject(DomSanitizer);

  /**
   * The diff line to display
   */
  readonly line = input.required<DiffLine>();

  /**
   * Theme for styling
   */
  readonly theme = input<CodeViewerTheme>('dark');

  /**
   * Whether to show line numbers
   */
  readonly showLineNumbers = input<boolean>(true);

  /**
   * Whether to show the +/- prefix
   */
  readonly showPrefix = input<boolean>(true);

  /**
   * Whether this line is highlighted (hovered)
   */
  readonly isHighlighted = input<boolean>(false);

  /**
   * Unique index for this line (used for hover tracking)
   */
  readonly lineIndex = input<number>(0);

  /**
   * Emits when mouse enters/leaves this line
   */
  readonly lineHover = output<number>();

  /**
   * Line widget configurations
   */
  readonly lineWidgets = input<LineWidgetsInput>();

  /**
   * Whether to show widgets (for hover display mode)
   */
  readonly showWidgets = input<boolean>(false);

  /**
   * Emits when a line widget is clicked
   */
  readonly lineWidgetClick = output<LineWidgetClickEvent>();

  /**
   * Computed CSS classes for the line container
   */
  protected readonly lineClasses = computed(() => {
    const lineType = this.line().type;
    const themeValue = this.theme();
    const highlighted = this.isHighlighted() ? 'highlighted' : '';
    return `diff-line ${lineType} ${themeValue} ${highlighted}`.trim();
  });

  /**
   * Computed prefix character (+, -, or space)
   */
  protected readonly prefix = computed(() => {
    return getDiffLinePrefix(this.line().type);
  });

  /**
   * Computed old line number display
   */
  protected readonly oldLineNum = computed(() => {
    const num = this.line().oldLineNumber;
    return num !== undefined ? String(num) : '';
  });

  /**
   * Computed new line number display
   */
  protected readonly newLineNum = computed(() => {
    const num = this.line().newLineNumber;
    return num !== undefined ? String(num) : '';
  });

  /**
   * Plain text content (for fallback)
   */
  protected readonly content = computed(() => this.line().content);

  /**
   * Whether this line has highlighted content
   */
  protected readonly hasHighlightedContent = computed(
    () => !!this.line().highlightedContent
  );

  /**
   * Highlighted HTML content (sanitized for safe rendering)
   */
  protected readonly highlightedContent = computed<SafeHtml>(() => {
    const content = this.line().highlightedContent ?? '';
    return this.sanitizer.bypassSecurityTrustHtml(content);
  });

  /**
   * Handle mouse enter event
   */
  protected onMouseEnter(): void {
    this.lineHover.emit(this.lineIndex());
  }

  /**
   * Get line number for context (prefer new line number, fallback to old)
   */
  protected readonly lineNumber = computed(() => {
    return this.line().newLineNumber ?? this.line().oldLineNumber ?? 0;
  });

  /**
   * Matching widgets for 'always' display
   */
  protected readonly alwaysWidgets = computed(() => {
    const widgets = this.lineWidgets();
    if (!widgets) return [];
    return getMatchingWidgets(widgets, this.content(), this.lineNumber()).filter(
      w => w.display === 'always'
    );
  });

  /**
   * Matching widgets for 'hover' display
   */
  protected readonly hoverWidgets = computed(() => {
    const widgets = this.lineWidgets();
    if (!widgets) return [];
    return getMatchingWidgets(widgets, this.content(), this.lineNumber()).filter(
      w => w.display === 'hover'
    );
  });

  /**
   * Widgets positioned on the left
   */
  protected readonly leftWidgets = computed(() => {
    const always = this.alwaysWidgets().filter(w => w.position === 'left');
    const hover =
      this.showWidgets() || this.isHighlighted()
        ? this.hoverWidgets().filter(w => w.position === 'left')
        : [];
    return [...always, ...hover];
  });

  /**
   * Widgets positioned on the right
   */
  protected readonly rightWidgets = computed(() => {
    const always = this.alwaysWidgets().filter(w => w.position === 'right');
    const hover =
      this.showWidgets() || this.isHighlighted()
        ? this.hoverWidgets().filter(w => w.position === 'right')
        : [];
    return [...always, ...hover];
  });

  /**
   * Context object for widget components
   */
  protected readonly widgetContext = computed<LineWidgetContext>(() => ({
    line: this.content(),
    lineNumber: this.lineNumber(),
    theme: this.theme(),
  }));

  /**
   * Handle widget click
   */
  protected onWidgetClick(widget: LineWidgetConfig): void {
    this.lineWidgetClick.emit({
      lineNumber: this.lineNumber(),
      line: this.content(),
      widget,
    });
  }
}

<div [class]="lineClasses()" (mouseenter)="onMouseEnter()">
  <!-- Left widgets container -->
  @if (leftWidgets().length > 0) {
    <div class="line-widgets-left">
      @for (widget of leftWidgets(); track $index) {
        <nx-line-widget-host
          [component]="widget.lineComponent"
          [context]="widgetContext()"
          [position]="'left'"
          [theme]="theme()"
          (widgetClick)="onWidgetClick(widget)" />
      }
    </div>
  }

  @if (showLineNumbers()) {
    <span class="line-number old">{{ oldLineNum() }}</span>
    <span class="line-number new">{{ newLineNum() }}</span>
  }
  @if (showPrefix()) {
    <span class="prefix">{{ prefix() }}</span>
  }
  @if (hasHighlightedContent()) {
    <span class="content" [innerHTML]="highlightedContent()"></span>
  } @else {
    <span class="content">{{ content() }}</span>
  }

  <!-- Right widgets container -->
  @if (rightWidgets().length > 0) {
    <div class="line-widgets-right">
      @for (widget of rightWidgets(); track $index) {
        <nx-line-widget-host
          [component]="widget.lineComponent"
          [context]="widgetContext()"
          [position]="'right'"
          [theme]="theme()"
          (widgetClick)="onWidgetClick(widget)" />
      }
    </div>
  }
</div>

// packages/client/ui/nx-vue-code-viewer/src/lib/atoms/diff-line/DiffLine.vue
<template>
  <div class="nx-diff-line">
  <div :class="lineClasses" @mouseenter="onMouseEnter">
    <!-- Left widgets -->
    <div v-if="leftWidgets.length > 0" class="line-widgets-left">
      <div
        v-for="(widget, i) in leftWidgets"
        :key="`left-${i}`"
        @click="onWidgetClick(widget)"
      >
        <component :is="widget.lineComponent" v-bind="widgetContext" />
      </div>
    </div>

    <span v-if="showLineNumbers" class="line-number old">{{ oldLineNum }}</span>
    <span v-if="showLineNumbers" class="line-number new">{{ newLineNum }}</span>
    <span v-if="showPrefix" class="prefix">{{ prefix }}</span>
    <span v-if="hasHighlightedContent" class="content" v-html="highlightedContent" />
    <span v-else class="content">{{ content }}</span>

    <!-- Right widgets -->
    <div v-if="rightWidgets.length > 0" class="line-widgets-right">
      <div
        v-for="(widget, i) in rightWidgets"
        :key="`right-${i}`"
        @click="onWidgetClick(widget)"
      >
        <component :is="widget.lineComponent" v-bind="widgetContext" />
      </div>
    </div>
  </div>
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue';
import {
  getDiffLinePrefix,
  getMatchingWidgets,
  type CodeViewerTheme,
  type DiffLine,
  type LineWidgetContext,
} from '@ngeenx/nx-code-viewer-utils';
import type { VueLineWidgetsInput, VueLineWidgetConfig, VueLineWidgetClickEvent } from '../../types/vue-code-viewer.types';

interface Props {
  line: DiffLine;
  theme?: CodeViewerTheme;
  showLineNumbers?: boolean;
  showPrefix?: boolean;
  isHighlighted?: boolean;
  lineIndex?: number;
  lineWidgets?: VueLineWidgetsInput;
  showWidgets?: boolean;
}

const props = withDefaults(defineProps<Props>(), {
  theme: 'dark',
  showLineNumbers: true,
  showPrefix: true,
  isHighlighted: false,
  lineIndex: 0,
  lineWidgets: () => [],
  showWidgets: false,
});

const emit = defineEmits<{
  lineHover: [lineIndex: number];
  lineWidgetClick: [event: VueLineWidgetClickEvent];
}>();

const lineClasses = computed(() => {
  const highlighted = props.isHighlighted ? 'highlighted' : '';
  return `diff-line ${props.line.type} ${props.theme} ${highlighted}`.trim();
});

const prefix = computed(() => getDiffLinePrefix(props.line.type));
const oldLineNum = computed(() => props.line.oldLineNumber !== undefined ? String(props.line.oldLineNumber) : '');
const newLineNum = computed(() => props.line.newLineNumber !== undefined ? String(props.line.newLineNumber) : '');
const content = computed(() => props.line.content);
const hasHighlightedContent = computed(() => !!props.line.highlightedContent);
const highlightedContent = computed(() => props.line.highlightedContent ?? '');
const lineNumber = computed(() => props.line.newLineNumber ?? props.line.oldLineNumber ?? 0);

const alwaysWidgets = computed<VueLineWidgetConfig[]>(() => {
  if (!props.lineWidgets?.length) return [];
  return (getMatchingWidgets(props.lineWidgets as any, content.value, lineNumber.value) as VueLineWidgetConfig[]).filter(w => w.display === 'always');
});

const hoverWidgets = computed<VueLineWidgetConfig[]>(() => {
  if (!props.lineWidgets?.length) return [];
  return (getMatchingWidgets(props.lineWidgets as any, content.value, lineNumber.value) as VueLineWidgetConfig[]).filter(w => w.display === 'hover');
});

const leftWidgets = computed(() => {
  const always = alwaysWidgets.value.filter(w => w.position === 'left');
  const hover = (props.showWidgets || props.isHighlighted) ? hoverWidgets.value.filter(w => w.position === 'left') : [];
  return [...always, ...hover];
});

const rightWidgets = computed(() => {
  const always = alwaysWidgets.value.filter(w => w.position === 'right');
  const hover = (props.showWidgets || props.isHighlighted) ? hoverWidgets.value.filter(w => w.position === 'right') : [];
  return [...always, ...hover];
});

const widgetContext = computed<LineWidgetContext>(() => ({
  line: content.value,
  lineNumber: lineNumber.value,
  theme: props.theme,
}));

function onMouseEnter(): void {
  emit('lineHover', props.lineIndex);
}

function onWidgetClick(widget: VueLineWidgetConfig): void {
  emit('lineWidgetClick', {
    lineNumber: lineNumber.value,
    line: content.value,
    widget,
  });
}
</script>
