// packages/client/ui/nx-angular-code-viewer/src/lib/atoms/line-numbers/line-numbers.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  computed,
  input,
  output,
} from '@angular/core';
import type {
  ActiveInsertWidget,
  CodeViewerTheme,
  CollapsedRangeState,
  LineRange,
} from '@ngeenx/nx-code-viewer-utils';
import {
  generateLineNumbers,
  formatLineNumber,
  isLineInCollapsedRange,
} from '@ngeenx/nx-code-viewer-utils';

/**
 * LineNumbers Atom Component
 *
 * Displays line numbers for code blocks.
 * Automatically generates and formats line numbers based on total line count.
 *
 * @example
 * ```html
 * <nx-line-numbers
 *   [lineCount]="10"
 *   [theme]="'dark'"
 * />
 * ```
 */
@Component({
  selector: 'nx-line-numbers',
  standalone: true,
  imports: [],
  templateUrl: './line-numbers.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { class: 'nx-line-numbers' },
})
export class LineNumbersComponent {
  /**
   * Total number of lines to display
   */
  readonly lineCount = input.required<number>();

  /**
   * Theme for styling
   */
  readonly theme = input<CodeViewerTheme>('dark');

  /**
   * Currently hovered line (1-based, 0 means no line hovered)
   */
  readonly hoveredLine = input<number>(0);

  /**
   * Set of pre-configured highlighted line numbers
   */
  readonly highlightedLinesSet = input<Set<number>>(new Set());

  /**
   * Map of collapsed range states
   */
  readonly collapsedRangesState = input<Map<string, CollapsedRangeState>>(
    new Map()
  );

  /**
   * Emitted when a line is hovered
   */
  readonly lineHover = output<number>();

  /**
   * Emitted when a collapsed range indicator is clicked
   */
  readonly collapsedRangeToggle = output<LineRange>();

  /**
   * Currently active insert widget (if any)
   */
  readonly activeInsertWidget = input<ActiveInsertWidget | null>(null);

  /**
   * Height of the active insert widget in pixels
   */
  readonly insertWidgetHeight = input<number>(0);

  /**
   * Computed array of line numbers
   */
  protected readonly lineNumbers = computed(() => {
    return generateLineNumbers(this.lineCount());
  });

  /**
   * Formats a line number with consistent width
   * @param lineNumber - Line number to format
   * @returns Formatted line number string
   */
  protected formatLine(lineNumber: number): string {
    return formatLineNumber(lineNumber, this.lineCount());
  }

  /**
   * TrackBy function for ngFor optimization
   */
  protected trackByLineNumber(_: number, lineNumber: number): number {
    return lineNumber;
  }

  /**
   * Checks if a line is currently hovered
   */
  protected isHovered(lineNumber: number): boolean {
    return this.hoveredLine() === lineNumber;
  }

  /**
   * Checks if a line is pre-configured as highlighted
   */
  protected isHighlighted(lineNumber: number): boolean {
    return this.highlightedLinesSet().has(lineNumber);
  }

  /**
   * Handles mouseenter on a line number
   */
  protected onMouseEnter(lineNumber: number): void {
    this.lineHover.emit(lineNumber);
  }

  /**
   * Gets collapse info for a line number
   */
  protected getLineCollapseInfo(lineNumber: number): {
    isCollapsed: boolean;
    isFirstLine: boolean;
    range: LineRange | null;
    hiddenCount: number;
  } {
    return isLineInCollapsedRange(lineNumber, this.collapsedRangesState());
  }

  /**
   * Handles click on expand toggle
   */
  protected onExpandToggle(range: LineRange): void {
    this.collapsedRangeToggle.emit(range);
  }

  /**
   * Checks if a line should be visible (not in a collapsed range, except first line)
   */
  protected isLineVisible(lineNumber: number): boolean {
    const collapseInfo = this.getLineCollapseInfo(lineNumber);
    return !collapseInfo.isCollapsed || collapseInfo.isFirstLine;
  }

  /**
   * Checks if an insert widget should appear after this line
   */
  protected hasInsertWidgetAfter(lineNumber: number): boolean {
    const widget = this.activeInsertWidget();
    return widget !== null && widget.lineNumber === lineNumber;
  }
}

<div class="line-numbers-container" [class]="theme()" aria-hidden="true">
  @for (
    lineNumber of lineNumbers();
    track trackByLineNumber($index, lineNumber)
  ) {
    @let collapseInfo = getLineCollapseInfo(lineNumber);

    @if (isLineVisible(lineNumber)) {
      <!-- Regular line number or first line of collapsed range -->
      <div
        class="line-number"
        [class.hovered]="isHovered(lineNumber)"
        [class.highlighted]="isHighlighted(lineNumber)"
        [class.collapsed-first]="collapseInfo.isFirstLine"
        (mouseenter)="onMouseEnter(lineNumber)">
        {{ formatLine(lineNumber) }}
      </div>

      <!-- Show collapse indicator row after first line of collapsed range -->
      @if (collapseInfo.isFirstLine && collapseInfo.range) {
        <div
          class="line-number collapse-indicator"
          role="button"
          tabindex="0"
          [attr.aria-label]="
            'Expand ' +
            collapseInfo.hiddenCount +
            ' hidden ' +
            (collapseInfo.hiddenCount === 1 ? 'line' : 'lines')
          "
          (click)="onExpandToggle(collapseInfo.range)"
          (keydown.enter)="onExpandToggle(collapseInfo.range)"
          (keydown.space)="onExpandToggle(collapseInfo.range); $event.preventDefault()">
          <svg
            viewBox="0 0 24 24"
            width="18"
            height="18"
            fill="none"
            stroke="currentColor"
            stroke-width="2"
            stroke-linecap="round"
            stroke-linejoin="round">
            <path d="m7 15 5 5 5-5" />
            <path d="m7 9 5-5 5 5" />
          </svg>
        </div>
      }

      <!-- Empty placeholder for insert widget (syncs line numbers with code rows) -->
      @if (hasInsertWidgetAfter(lineNumber)) {
        <div
          class="insert-widget-placeholder"
          [style.height.px]="insertWidgetHeight()">
        </div>
      }
    }
  }
</div>

// packages/client/ui/nx-vue-code-viewer/src/lib/atoms/line-numbers/LineNumbers.vue
<template>
  <div class="line-numbers-container" :class="theme" aria-hidden="true">
    <template v-for="lineNumber in lineNumbers" :key="lineNumber">
      <template v-if="isLineVisible(lineNumber)">
        <div
          class="line-number"
          :class="{
            hovered: isHovered(lineNumber),
            highlighted: isHighlighted(lineNumber),
            'collapsed-first': getLineCollapseInfo(lineNumber).isFirstLine,
          }"
          @mouseenter="onMouseEnter(lineNumber)"
        >
          {{ formatLine(lineNumber) }}
        </div>

        <div
          v-if="getLineCollapseInfo(lineNumber).isFirstLine && getLineCollapseInfo(lineNumber).range"
          class="line-number collapse-indicator"
          role="button"
          tabindex="0"
          :aria-label="`Expand ${getLineCollapseInfo(lineNumber).hiddenCount} hidden ${getLineCollapseInfo(lineNumber).hiddenCount === 1 ? 'line' : 'lines'}`"
          @click="onExpandToggle(getLineCollapseInfo(lineNumber).range!)"
          @keydown.enter="onExpandToggle(getLineCollapseInfo(lineNumber).range!)"
          @keydown.space.prevent="onExpandToggle(getLineCollapseInfo(lineNumber).range!)"
        >
          <svg viewBox="0 0 24 24" width="18" height="18" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
            <path d="m7 15 5 5 5-5" />
            <path d="m7 9 5-5 5 5" />
          </svg>
        </div>

        <div
          v-if="hasInsertWidgetAfter(lineNumber)"
          class="insert-widget-placeholder"
          :style="{ height: insertWidgetHeight + 'px' }"
        />
      </template>
    </template>
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue';
import {
  generateLineNumbers,
  formatLineNumber,
  isLineInCollapsedRange,
  type CodeViewerTheme,
  type CollapsedRangeState,
  type LineRange,
} from '@ngeenx/nx-code-viewer-utils';
import type { VueActiveInsertWidget } from '../../types/vue-code-viewer.types';

interface Props {
  lineCount: number;
  theme?: CodeViewerTheme;
  hoveredLine?: number;
  highlightedLinesSet?: Set<number>;
  collapsedRangesState?: Map<string, CollapsedRangeState>;
  activeInsertWidget?: VueActiveInsertWidget | null;
  insertWidgetHeight?: number;
}

const props = withDefaults(defineProps<Props>(), {
  theme: 'dark',
  hoveredLine: 0,
  highlightedLinesSet: () => new Set(),
  collapsedRangesState: () => new Map(),
  activeInsertWidget: null,
  insertWidgetHeight: 0,
});

const emit = defineEmits<{
  lineHover: [lineNumber: number];
  collapsedRangeToggle: [range: LineRange];
}>();

const lineNumbers = computed(() => generateLineNumbers(props.lineCount));

function formatLine(lineNumber: number): string {
  return formatLineNumber(lineNumber, props.lineCount);
}

function isHovered(lineNumber: number): boolean {
  return props.hoveredLine === lineNumber;
}

function isHighlighted(lineNumber: number): boolean {
  return props.highlightedLinesSet.has(lineNumber);
}

function getLineCollapseInfo(lineNumber: number) {
  return isLineInCollapsedRange(lineNumber, props.collapsedRangesState);
}

function isLineVisible(lineNumber: number): boolean {
  const info = getLineCollapseInfo(lineNumber);
  return !info.isCollapsed || info.isFirstLine;
}

function hasInsertWidgetAfter(lineNumber: number): boolean {
  return props.activeInsertWidget !== null && props.activeInsertWidget?.lineNumber === lineNumber;
}

function onMouseEnter(lineNumber: number): void {
  emit('lineHover', lineNumber);
}

function onExpandToggle(range: LineRange): void {
  emit('collapsedRangeToggle', range);
}
</script>
