// packages/client/ui/nx-angular-code-viewer/src/lib/atoms/collapsed-indicator/collapsed-indicator.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  computed,
  input,
  output,
} from '@angular/core';
import type { CodeViewerTheme, LineRange } from '@ngeenx/nx-code-viewer-utils';

/**
 * CollapsedIndicator Atom Component
 *
 * Displays a row indicating that lines are collapsed, with an expand/collapse toggle.
 * Shows the number of hidden lines and provides click-to-expand functionality.
 *
 * @example
 * ```html
 * <nx-collapsed-indicator
 *   [theme]="'dark'"
 *   [range]="[10, 20]"
 *   [hiddenCount]="10"
 *   [isExpanded]="false"
 *   (toggle)="onToggle()"
 * />
 * ```
 */
@Component({
  selector: 'nx-collapsed-indicator',
  imports: [],
  templateUrl: './collapsed-indicator.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { class: 'nx-collapsed-indicator' },
})
export class CollapsedIndicatorComponent {
  /**
   * Theme for styling
   */
  readonly theme = input<CodeViewerTheme>('dark');

  /**
   * The line range that is collapsed
   */
  readonly range = input.required<LineRange>();

  /**
   * Number of hidden lines (lines after the first one)
   */
  readonly hiddenCount = input.required<number>();

  /**
   * Whether the range is currently expanded
   */
  readonly isExpanded = input<boolean>(false);

  /**
   * Emitted when the indicator is clicked to toggle expansion
   */
  readonly toggle = output<void>();

  /**
   * Computed display text for the indicator
   */
  protected readonly displayText = computed(() => {
    const count = this.hiddenCount();
    return count === 1 ? '1 line' : `${count} lines`;
  });

  /**
   * Computed aria label for accessibility
   */
  protected readonly ariaLabel = computed(() => {
    const count = this.hiddenCount();
    const expanded = this.isExpanded();
    const lines = count === 1 ? 'line' : 'lines';
    return expanded
      ? `Collapse ${count} ${lines}`
      : `Expand ${count} hidden ${lines}`;
  });

  /**
   * Handles click on the indicator
   */
  protected onToggle(): void {
    this.toggle.emit();
  }

  /**
   * Handles keyboard activation
   */
  protected onKeydown(event: KeyboardEvent): void {
    if (event.key === 'Enter' || event.key === ' ') {
      event.preventDefault();
      this.toggle.emit();
    }
  }
}

<div
  class="collapsed-indicator"
  [class]="theme()"
  [class.expanded]="isExpanded()"
  role="button"
  tabindex="0"
  [attr.aria-expanded]="isExpanded()"
  [attr.aria-label]="ariaLabel()"
  (click)="onToggle()"
  (keydown)="onKeydown($event)">
  <!-- Expand/collapse icon in line number area -->
  <span class="expand-icon">
    @if (isExpanded()) {
      <!-- Chevron down icon -->
      <svg
        viewBox="0 0 16 16"
        width="12"
        height="12"
        fill="none"
        stroke="currentColor"
        stroke-width="1.5"
        stroke-linecap="round"
        stroke-linejoin="round">
        <path d="M4 6l4 4 4-4" />
      </svg>
    } @else {
      <!-- Chevron right icon -->
      <svg
        viewBox="0 0 16 16"
        width="12"
        height="12"
        fill="none"
        stroke="currentColor"
        stroke-width="1.5"
        stroke-linecap="round"
        stroke-linejoin="round">
        <path d="M6 4l4 4-4 4" />
      </svg>
    }
  </span>

  <!-- Ellipsis and line count -->
  <span class="collapse-text"> ... {{ displayText() }} </span>
</div>

// packages/client/ui/nx-react-code-viewer/src/lib/atoms/collapsed-indicator/CollapsedIndicator.tsx
import { memo, useMemo } from 'react';
import type { CodeViewerTheme, LineRange } from '@ngeenx/nx-code-viewer-utils';

interface CollapsedIndicatorProps {
  theme?: CodeViewerTheme;
  range: LineRange;
  hiddenCount: number;
  isExpanded?: boolean;
  onToggle?: () => void;
}

export const CollapsedIndicator = memo(function CollapsedIndicator({
  theme = 'dark',
  range,
  hiddenCount,
  isExpanded = false,
  onToggle,
}: CollapsedIndicatorProps) {
  const displayText = useMemo(() => {
    return hiddenCount === 1 ? '1 line' : `${hiddenCount} lines`;
  }, [hiddenCount]);

  const ariaLabel = useMemo(() => {
    const lines = hiddenCount === 1 ? 'line' : 'lines';
    return isExpanded
      ? `Collapse ${hiddenCount} ${lines}`
      : `Expand ${hiddenCount} hidden ${lines}`;
  }, [hiddenCount, isExpanded]);

  const handleKeydown = (event: React.KeyboardEvent) => {
    if (event.key === 'Enter' || event.key === ' ') {
      event.preventDefault();
      onToggle?.();
    }
  };

  return (
    <div className="nx-collapsed-indicator">
      <div
        className={`collapsed-indicator ${theme} ${isExpanded ? 'expanded' : ''}`}
        role="button"
        tabIndex={0}
        aria-expanded={isExpanded}
        aria-label={ariaLabel}
        onClick={onToggle}
        onKeyDown={handleKeydown}
      >
        <span className="expand-icon">
          <svg viewBox="0 0 24 24" width="18" height="18" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
            <path d="m7 15 5 5 5-5" />
            <path d="m7 9 5-5 5 5" />
          </svg>
        </span>
        <span className="collapse-text"> ... {displayText} </span>
      </div>
    </div>
  );
});
