// packages/client/ui/nx-vue-code-viewer/src/lib/molecules/code-block/CodeBlock.vue
<template>
  <div class="nx-code-block">
  <div class="code-block-wrapper">
    <CopyButton
      v-if="showCopyButton"
      class="copy-button"
      :state="copyState"
      :theme="theme"
      @copy-click="onCopyClick"
    />

    <div
      class="code-block-container"
      :style="containerStyle"
      @mouseleave="onLineHover(0)"
    >
      <LineNumbers
        v-if="showLineNumbers"
        :lineCount="lineCount"
        :theme="theme"
        :hoveredLine="hoveredLine"
        :highlightedLinesSet="highlightedLinesSet"
        :collapsedRangesState="collapsedRangesState"
        :activeInsertWidget="activeInsertWidget"
        :insertWidgetHeight="insertWidgetHeight"
        @line-hover="onLineHover"
        @collapsed-range-toggle="onCollapsedRangeToggle"
      />

      <CodeContent
        :content="content"
        :rawCode="rawCode"
        :theme="theme"
        :wordWrap="wordWrap"
        :isLoading="isLoading"
        :hoveredLine="hoveredLine"
        :highlightedLinesSet="highlightedLinesSet"
        :focusedLinesSet="focusedLinesSet"
        :collapsedRangesState="collapsedRangesState"
        :processedReferences="processedReferences"
        :lineWidgets="lineWidgets"
        :activeInsertWidget="activeInsertWidget"
        @line-hover="onLineHover"
        @reference-click="onReferenceClick"
        @reference-hover="onReferenceHover"
        @collapsed-range-toggle="onCollapsedRangeToggle"
        @line-widget-click="onLineWidgetClick"
        @insert-widget-close="onInsertWidgetClose"
        @insert-widget-height-change="onInsertWidgetHeightChange"
      />
    </div>
  </div>
  </div>
</template>

<script setup lang="ts">
import { ref, computed } from 'vue';
import type {
  CodeViewerTheme,
  CollapsedRangeState,
  LineRange,
  ProcessedReference,
  ReferenceHoverEvent,
} from '@ngeenx/nx-code-viewer-utils';
import type {
  VueLineWidgetsInput,
  VueActiveInsertWidget,
  VueLineWidgetClickEvent,
} from '../../types/vue-code-viewer.types';
import type { CopyButtonState } from '@ngeenx/nx-code-viewer-utils';
import { CodeContent } from '../../atoms/code-content';
import { LineNumbers } from '../../atoms/line-numbers';
import { CopyButton } from '../../atoms/copy-button';

interface Props {
  content: string | null;
  rawCode?: string;
  lineCount: number;
  theme?: CodeViewerTheme;
  showLineNumbers?: boolean;
  enableLineHover?: boolean;
  wordWrap?: boolean;
  maxHeight?: string;
  isLoading?: boolean;
  showCopyButton?: boolean;
  copyState?: CopyButtonState;
  copyClick?: () => void;
  highlightedLinesSet?: Set<number>;
  focusedLinesSet?: Set<number>;
  processedReferences?: Map<string, ProcessedReference>;
  collapsedRangesState?: Map<string, CollapsedRangeState>;
  lineWidgets?: VueLineWidgetsInput;
}

const props = withDefaults(defineProps<Props>(), {
  rawCode: '',
  theme: 'dark',
  showLineNumbers: true,
  enableLineHover: true,
  wordWrap: false,
  maxHeight: '',
  isLoading: false,
  showCopyButton: true,
  copyState: 'idle',
  copyClick: () => {},
  highlightedLinesSet: () => new Set(),
  focusedLinesSet: () => new Set(),
  processedReferences: () => new Map(),
  collapsedRangesState: () => new Map(),
  lineWidgets: () => [],
});

const emit = defineEmits<{
  referenceClick: [reference: ProcessedReference];
  referenceHover: [event: ReferenceHoverEvent];
  collapsedRangeToggle: [range: LineRange];
  lineWidgetClick: [event: VueLineWidgetClickEvent];
}>();

const hoveredLine = ref<number>(0);
const activeInsertWidget = ref<VueActiveInsertWidget | null>(null);
const insertWidgetHeight = ref<number>(0);

const containerStyle = computed(() => {
  return props.maxHeight ? { 'max-height': props.maxHeight } : {};
});

function onLineHover(lineNumber: number): void {
  if (!props.enableLineHover) return;
  hoveredLine.value = lineNumber;
}

function onCopyClick(): void {
  props.copyClick();
}

function onReferenceClick(reference: ProcessedReference): void {
  emit('referenceClick', reference);
}

function onReferenceHover(event: ReferenceHoverEvent): void {
  emit('referenceHover', event);
}

function onCollapsedRangeToggle(range: LineRange): void {
  emit('collapsedRangeToggle', range);
}

function onLineWidgetClick(event: VueLineWidgetClickEvent): void {
  const current = activeInsertWidget.value;

  if (current && current.lineNumber === event.lineNumber && current.widget === event.widget) {
    activeInsertWidget.value = null;
  } else if (event.widget.insertComponent) {
    activeInsertWidget.value = {
      lineNumber: event.lineNumber,
      widget: event.widget,
      line: event.line,
    };
  }

  emit('lineWidgetClick', event);
}

function onInsertWidgetClose(): void {
  activeInsertWidget.value = null;
}

function onInsertWidgetHeightChange(height: number): void {
  insertWidgetHeight.value = height;
}
</script>

// packages/client/ui/nx-svelte-code-viewer/src/lib/molecules/CodeBlock.svelte
<script lang="ts">
  import type {
    CodeViewerTheme,
    CollapsedRangeState,
    LineRange,
    ProcessedReference,
    ReferenceHoverEvent,
    CopyButtonState,
  } from '@ngeenx/nx-code-viewer-utils';
  import type { SvelteLineWidgetsInput, SvelteLineWidgetClickEvent, SvelteActiveInsertWidget } from '../types/svelte-code-viewer.types';
  import CopyButton from '../atoms/CopyButton.svelte';
  import LineNumbers from '../atoms/LineNumbers.svelte';
  import CodeContent from '../atoms/CodeContent.svelte';

  interface Props {
    content: string | null;
    rawCode?: string;
    lineCount: number;
    theme?: CodeViewerTheme;
    showLineNumbers?: boolean;
    enableLineHover?: boolean;
    wordWrap?: boolean;
    maxHeight?: string;
    isLoading?: boolean;
    showCopyButton?: boolean;
    copyState?: CopyButtonState;
    copyClick?: () => void;
    highlightedLinesSet?: Set<number>;
    focusedLinesSet?: Set<number>;
    collapsedRangesState?: Map<string, CollapsedRangeState>;
    processedReferences?: Map<string, ProcessedReference>;
    lineWidgets?: SvelteLineWidgetsInput;
    onReferenceClick?: (reference: ProcessedReference) => void;
    onReferenceHover?: (event: ReferenceHoverEvent) => void;
    onCollapsedRangeToggle?: (range: LineRange) => void;
    onLineWidgetClick?: (event: SvelteLineWidgetClickEvent) => void;
  }

  let {
    content,
    rawCode = '',
    lineCount,
    theme = 'dark',
    showLineNumbers = true,
    enableLineHover = true,
    wordWrap = false,
    maxHeight = '',
    isLoading = false,
    showCopyButton = true,
    copyState = 'idle',
    copyClick = () => {},
    highlightedLinesSet = new Set<number>(),
    focusedLinesSet = new Set<number>(),
    collapsedRangesState = new Map(),
    processedReferences = new Map(),
    lineWidgets = [],
    onReferenceClick = () => {},
    onReferenceHover = () => {},
    onCollapsedRangeToggle = () => {},
    onLineWidgetClick = () => {},
  }: Props = $props();

  let hoveredLine = $state(0);
  let activeInsertWidget: SvelteActiveInsertWidget | null = $state(null);
  let insertWidgetHeight = $state(0);

  const containerStyle = $derived(
    maxHeight ? `max-height: ${maxHeight}; overflow: auto;` : ''
  );

  function onLineHover(lineNumber: number): void {
    if (!enableLineHover) return;
    hoveredLine = lineNumber;
  }

  function handleLineWidgetClick(event: SvelteLineWidgetClickEvent): void {
    const currentActive = activeInsertWidget;

    if (
      currentActive &&
      currentActive.lineNumber === event.lineNumber &&
      currentActive.widget === event.widget
    ) {
      // Same widget clicked, close it
      activeInsertWidget = null;
    } else if (event.widget.insertComponent) {
      // Different widget with insert component, open it
      activeInsertWidget = {
        lineNumber: event.lineNumber,
        widget: event.widget,
        line: event.line,
      };
    }

    onLineWidgetClick(event);
  }

  function handleInsertWidgetClose(): void {
    activeInsertWidget = null;
  }

  function handleInsertWidgetHeightChange(height: number): void {
    insertWidgetHeight = height;
  }
</script>

<div class="nx-code-block">
  <div class="code-block-wrapper">
    {#if showCopyButton}
      <div class="copy-button">
        <CopyButton
          state={copyState}
          {theme}
          disabled={isLoading}
          onCopyClick={copyClick}
        />
      </div>
    {/if}

    <div class="code-block-container" style={containerStyle} onmouseleave={() => onLineHover(0)}>
      {#if showLineNumbers}
        <LineNumbers
          {lineCount}
          {theme}
          {hoveredLine}
          {highlightedLinesSet}
          {collapsedRangesState}
          {activeInsertWidget}
          {insertWidgetHeight}
          {onLineHover}
          {onCollapsedRangeToggle}
        />
      {/if}

      <CodeContent
        {content}
        {rawCode}
        {theme}
        {wordWrap}
        {isLoading}
        {hoveredLine}
        {highlightedLinesSet}
        {focusedLinesSet}
        {collapsedRangesState}
        {processedReferences}
        {lineWidgets}
        {activeInsertWidget}
        {onReferenceClick}
        {onReferenceHover}
        {onCollapsedRangeToggle}
        onLineWidgetClick={handleLineWidgetClick}
        onInsertWidgetClose={handleInsertWidgetClose}
        onInsertWidgetHeightChange={handleInsertWidgetHeightChange}
        onLineHover={onLineHover}
      />
    </div>
  </div>
</div>
