// packages/client/ui/nx-react-code-viewer/src/lib/molecules/code-block/CodeBlock.tsx
import React, { memo, useState, useMemo, useCallback } from 'react';
import type {
  ActiveInsertWidget,
  CodeViewerTheme,
  CollapsedRangeState,
  CopyButtonState,
  LineRange,
  LineWidgetClickEvent,
  LineWidgetsInput,
  ProcessedReference,
  ReferenceHoverEvent,
} from '@ngeenx/nx-code-viewer-utils';
import { LineNumbers } from '../../atoms/line-numbers';
import { CodeContent } from '../../atoms/code-content';
import { CopyButton } from '../../atoms/copy-button';

interface CodeBlockProps {
  content: string | null;
  rawCode?: string;
  lineCount: number;
  theme?: CodeViewerTheme;
  showLineNumbers?: boolean;
  enableLineHover?: boolean;
  wordWrap?: boolean;
  maxHeight?: string;
  isLoading?: boolean;
  showCopyButton?: boolean;
  copyState?: CopyButtonState;
  onCopyClick?: () => void;
  highlightedLinesSet?: Set<number>;
  focusedLinesSet?: Set<number>;
  processedReferences?: Map<string, ProcessedReference>;
  collapsedRangesState?: Map<string, CollapsedRangeState>;
  lineWidgets?: LineWidgetsInput;
  onReferenceClick?: (reference: ProcessedReference) => void;
  onReferenceHover?: (event: ReferenceHoverEvent) => void;
  onCollapsedRangeToggle?: (range: LineRange) => void;
  onLineWidgetClick?: (event: LineWidgetClickEvent) => void;
}

export const CodeBlock = memo(function CodeBlock({
  content,
  rawCode = '',
  lineCount,
  theme = 'dark',
  showLineNumbers = true,
  enableLineHover = true,
  wordWrap = false,
  maxHeight = '',
  isLoading = false,
  showCopyButton = true,
  copyState = 'idle',
  onCopyClick,
  highlightedLinesSet = new Set(),
  focusedLinesSet = new Set(),
  processedReferences = new Map(),
  collapsedRangesState = new Map(),
  lineWidgets = [],
  onReferenceClick,
  onReferenceHover,
  onCollapsedRangeToggle,
  onLineWidgetClick,
}: CodeBlockProps) {
  const [hoveredLine, setHoveredLine] = useState(0);
  const [activeInsertWidget, setActiveInsertWidget] = useState<ActiveInsertWidget | null>(null);
  const [insertWidgetHeight, setInsertWidgetHeight] = useState(0);

  const containerStyle = useMemo(() => {
    return maxHeight ? { maxHeight } : {};
  }, [maxHeight]);

  const handleLineHover = useCallback((lineNumber: number) => {
    if (!enableLineHover) return;
    setHoveredLine(lineNumber);
  }, [enableLineHover]);

  const handleLineWidgetClick = useCallback((event: LineWidgetClickEvent) => {
    const currentActive = activeInsertWidget;
    if (
      currentActive &&
      currentActive.lineNumber === event.lineNumber &&
      currentActive.widget === event.widget
    ) {
      setActiveInsertWidget(null);
    } else if (event.widget.insertComponent) {
      setActiveInsertWidget({
        lineNumber: event.lineNumber,
        widget: event.widget,
        line: event.line,
      });
    }

    onLineWidgetClick?.(event);
  }, [activeInsertWidget, onLineWidgetClick]);

  const handleInsertWidgetClose = useCallback(() => {
    setActiveInsertWidget(null);
  }, []);

  const handleInsertWidgetHeightChange = useCallback((height: number) => {
    setInsertWidgetHeight(height);
  }, []);

  return (
    <div className="nx-code-block">
      <div className="code-block-wrapper">
        {showCopyButton && (
          <div className="copy-button">
            <CopyButton
              state={copyState}
              theme={theme}
              onCopyClick={onCopyClick}
            />
          </div>
        )}

        <div
          className="code-block-container"
          style={containerStyle}
          onMouseLeave={() => handleLineHover(0)}
        >
          {showLineNumbers && (
            <LineNumbers
              lineCount={lineCount}
              theme={theme}
              hoveredLine={hoveredLine}
              highlightedLinesSet={highlightedLinesSet}
              collapsedRangesState={collapsedRangesState}
              activeInsertWidget={activeInsertWidget}
              insertWidgetHeight={insertWidgetHeight}
              onLineHover={handleLineHover}
              onCollapsedRangeToggle={onCollapsedRangeToggle}
            />
          )}

          <CodeContent
            content={content}
            rawCode={rawCode}
            theme={theme}
            wordWrap={wordWrap}
            isLoading={isLoading}
            hoveredLine={hoveredLine}
            highlightedLinesSet={highlightedLinesSet}
            focusedLinesSet={focusedLinesSet}
            collapsedRangesState={collapsedRangesState}
            processedReferences={processedReferences}
            lineWidgets={lineWidgets}
            activeInsertWidget={activeInsertWidget}
            onLineHover={handleLineHover}
            onReferenceClick={onReferenceClick}
            onReferenceHover={onReferenceHover}
            onCollapsedRangeToggle={onCollapsedRangeToggle}
            onLineWidgetClick={handleLineWidgetClick}
            onInsertWidgetClose={handleInsertWidgetClose}
            onInsertWidgetHeightChange={handleInsertWidgetHeightChange}
          />
        </div>
      </div>
    </div>
  );
});

// packages/client/ui/nx-svelte-code-viewer/src/lib/molecules/CodeBlock.svelte
<script lang="ts">
  import type {
    CodeViewerTheme,
    CollapsedRangeState,
    LineRange,
    ProcessedReference,
    ReferenceHoverEvent,
    CopyButtonState,
  } from '@ngeenx/nx-code-viewer-utils';
  import type { SvelteLineWidgetsInput, SvelteLineWidgetClickEvent, SvelteActiveInsertWidget } from '../types/svelte-code-viewer.types';
  import CopyButton from '../atoms/CopyButton.svelte';
  import LineNumbers from '../atoms/LineNumbers.svelte';
  import CodeContent from '../atoms/CodeContent.svelte';

  interface Props {
    content: string | null;
    rawCode?: string;
    lineCount: number;
    theme?: CodeViewerTheme;
    showLineNumbers?: boolean;
    enableLineHover?: boolean;
    wordWrap?: boolean;
    maxHeight?: string;
    isLoading?: boolean;
    showCopyButton?: boolean;
    copyState?: CopyButtonState;
    copyClick?: () => void;
    highlightedLinesSet?: Set<number>;
    focusedLinesSet?: Set<number>;
    collapsedRangesState?: Map<string, CollapsedRangeState>;
    processedReferences?: Map<string, ProcessedReference>;
    lineWidgets?: SvelteLineWidgetsInput;
    onReferenceClick?: (reference: ProcessedReference) => void;
    onReferenceHover?: (event: ReferenceHoverEvent) => void;
    onCollapsedRangeToggle?: (range: LineRange) => void;
    onLineWidgetClick?: (event: SvelteLineWidgetClickEvent) => void;
  }

  let {
    content,
    rawCode = '',
    lineCount,
    theme = 'dark',
    showLineNumbers = true,
    enableLineHover = true,
    wordWrap = false,
    maxHeight = '',
    isLoading = false,
    showCopyButton = true,
    copyState = 'idle',
    copyClick = () => {},
    highlightedLinesSet = new Set<number>(),
    focusedLinesSet = new Set<number>(),
    collapsedRangesState = new Map(),
    processedReferences = new Map(),
    lineWidgets = [],
    onReferenceClick = () => {},
    onReferenceHover = () => {},
    onCollapsedRangeToggle = () => {},
    onLineWidgetClick = () => {},
  }: Props = $props();

  let hoveredLine = $state(0);
  let activeInsertWidget: SvelteActiveInsertWidget | null = $state(null);
  let insertWidgetHeight = $state(0);

  const containerStyle = $derived(
    maxHeight ? `max-height: ${maxHeight}; overflow: auto;` : ''
  );

  function onLineHover(lineNumber: number): void {
    if (!enableLineHover) return;
    hoveredLine = lineNumber;
  }

  function handleLineWidgetClick(event: SvelteLineWidgetClickEvent): void {
    const currentActive = activeInsertWidget;

    if (
      currentActive &&
      currentActive.lineNumber === event.lineNumber &&
      currentActive.widget === event.widget
    ) {
      // Same widget clicked, close it
      activeInsertWidget = null;
    } else if (event.widget.insertComponent) {
      // Different widget with insert component, open it
      activeInsertWidget = {
        lineNumber: event.lineNumber,
        widget: event.widget,
        line: event.line,
      };
    }

    onLineWidgetClick(event);
  }

  function handleInsertWidgetClose(): void {
    activeInsertWidget = null;
  }

  function handleInsertWidgetHeightChange(height: number): void {
    insertWidgetHeight = height;
  }
</script>

<div class="nx-code-block">
  <div class="code-block-wrapper">
    {#if showCopyButton}
      <div class="copy-button">
        <CopyButton
          state={copyState}
          {theme}
          disabled={isLoading}
          onCopyClick={copyClick}
        />
      </div>
    {/if}

    <div class="code-block-container" style={containerStyle} onmouseleave={() => onLineHover(0)}>
      {#if showLineNumbers}
        <LineNumbers
          {lineCount}
          {theme}
          {hoveredLine}
          {highlightedLinesSet}
          {collapsedRangesState}
          {activeInsertWidget}
          {insertWidgetHeight}
          {onLineHover}
          {onCollapsedRangeToggle}
        />
      {/if}

      <CodeContent
        {content}
        {rawCode}
        {theme}
        {wordWrap}
        {isLoading}
        {hoveredLine}
        {highlightedLinesSet}
        {focusedLinesSet}
        {collapsedRangesState}
        {processedReferences}
        {lineWidgets}
        {activeInsertWidget}
        {onReferenceClick}
        {onReferenceHover}
        {onCollapsedRangeToggle}
        onLineWidgetClick={handleLineWidgetClick}
        onInsertWidgetClose={handleInsertWidgetClose}
        onInsertWidgetHeightChange={handleInsertWidgetHeightChange}
        onLineHover={onLineHover}
      />
    </div>
  </div>
</div>
